<a href="https://colab.research.google.com/github/Humaira201/Multiclass-Bangla-Smishing-Detection/blob/main/notebooks/Bangla_Smishing_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys

print("Python version:")
print(sys.version)

Python version:
3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected.")

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

In [5]:
import os

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"

print(os.listdir(PROJECT_DIR))

['dataset', 'models', 'outputs', 'results', 'notebooks']

In [6]:
import os

print(os.listdir("/content/drive/MyDrive"))

['Bangla_Smishing_Project', 'Classroom', 'lab work.gdoc', 'Untitled document (16).gdoc', 'lab (1).gdoc', 'lab2.gdoc', 'reading for cls lecture.gslides', 'CamScanner 11-13-2023 10.30.pdf', 'Untitled document (15).gdoc', 'Diffraction of light_CSE 22 (1).gdoc', 'Untitled document (14).gdoc', 'Untitled document (13).gdoc', 'Diffraction of light_CSE 22.gdoc', 'Untitled document (12).gdoc', 'Untitled document (11).gdoc', 'Untitled document (10).gdoc', 'wave shaping.gdoc', 'Untitled document (9).gdoc', '9_Lesson 9 Operator Overloading (2).gslides', 'Inheritance (2).gslides', '9_Lesson 9 Operator Overloading (1).gslides', 'Chapter 15.gdoc', 'Chapter 15.gslides', 'Chapter 16.gslides', 'lab.gdoc', 'Untitled document (8).gdoc', 'Chapter 13 (2).gslides', 'The.Complete.Reference Book.gdoc', 'oop_lab_task.gdoc', 'Chapter 13 (1).gslides', 'Chapter 14.gslides', 'Chapter 13.gslides', 'Chapter 12 (1).gslides', 'Chapter 11.gslides', 'Chapter 12.gslides', 'Inheritance (1).gslides', 'Inheritance.gslides', '9_Lesson 9 Operator Overloading.gslides', '8_Lesson 8 Methods and Classes.gslides', 'A-Textbook-of-Electrical-Technology-volume-4-by-theraja.gdoc', 'Untitled document (7).gdoc', 'Untitled document (6).gdoc', 'Untitled document (5).gdoc', 'Untitled document (4).gdoc', 'Untitled document (3).gdoc', 'Untitled document (2).gdoc', 'lab 01.gdoc', 'stack.gdoc', 'BST lab.gdoc', 'lab 02 cp.gdoc', 'dld.gdoc', 'heap and graph.gdoc', 'IntraBiz 1.0 Final Round Case.pdf', 'Colab Notebooks', 'CUET_Algoristas_IntraBiz1.0_Slide', 'DM Sans.pptx', 'DM Sans (1).pdf', 'Screenshot 2025-07-30 at 23-21-58 (2) Instagram.png', 'Ummay Habiba.png', 'Ummay Habiba.pdf', 'DSP lab 01.gdoc', 'algorithm lab.gdoc', 'Some problems related Harmonoc functions3-01-2023 20.12.gdoc', '4th Digital Signal Processing - Proakis and Manolakis (2).gdoc', 'dsp lab 02.gdoc', 'algorithm lab 02.gdoc', 'dsp lab 03 .gdoc', 'algorithm lab 03.gdoc', 'dsp lab 04.gdoc', 'Project_Onnomitro', 'Zeros and Singularity.gdoc', 'Database implementation.gdoc', 'algolab 4.gdoc', '2204001_A.cpp', '2204001_B.cpp', '2204001_C.cpp', '2204001_D.cpp', '2204001_A.o', '2204001_A.exe', '2204001_B.o', '2204001_B.exe', '2204001_C.exe', '2204001_C.o', '2204001_D.o', '2204001_D.exe', 'PCM implementation.gdoc', 'Linux Shell Command.gdoc', 'Untitled document (1).gdoc', 'Untitled document.gdoc', 'rice disease.gdoc', 'IP.gdoc', 'bio.gdoc', 'SWE proposal report(campusKart).gdoc', 'cloud task scheduling.gdoc', 'Static Routing.gdoc', 'Corrected_AI_Traffic_Signal_Report (1).gdoc', 'Issue log.gdoc', 'highlighted corrected report.gdoc', 'Corrected_AI_Traffic_Signal_Report.gdoc', 'Issue log found in the original report.gdoc', 'Corrected_Report_With_Highlighted_Corrections.gdoc', 'Bengali Deepfake research(my scope).gdoc', 'Literature Limitations .gdoc', 'Copy of technical humaira(2204001).pdf']

In [9]:
import os

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"

DATA_DIR = os.path.join(PROJECT_DIR, "dataset")
NOTEBOOK_DIR = os.path.join(PROJECT_DIR, "notebooks")
MODEL_DIR = os.path.join(PROJECT_DIR, "models")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "outputs")
RESULTS_DIR = os.path.join(PROJECT_DIR, "results")

CSV_PATH = os.path.join(DATA_DIR, "bangla_smishing_preprocessed.csv")

print("CSV path:")
print(CSV_PATH)

CSV path:
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/bangla_smishing_preprocessed.csv

In [10]:
import os

if os.path.exists(CSV_PATH):
    print("✅ Dataset found!")
else:
    print("❌ Dataset NOT found!")

✅ Dataset found!

In [11]:
!pip install -q pandas==2.2.3 "numpy>=1.24,<2.3"

In [13]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.2.3
NumPy: 2.1.3

In [14]:
import transformers
import datasets
import accelerate
import sklearn

print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("Accelerate:", accelerate.__version__)
print("Scikit-learn:", sklearn.__version__)

Transformers: 5.15.1
Datasets: 4.0.0
Accelerate: 1.14.0
Scikit-learn: 1.6.1

In [15]:
import sys
import torch

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: GPU not detected")

Python: 3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

In [16]:
folders = [
    PROJECT_DIR,
    DATA_DIR,
    NOTEBOOK_DIR,
    MODEL_DIR,
    OUTPUT_DIR,
    RESULTS_DIR
]

for folder in folders:
    print(folder, "->", os.path.exists(folder))

/content/drive/MyDrive/Bangla_Smishing_Project -> True
/content/drive/MyDrive/Bangla_Smishing_Project/dataset -> True
/content/drive/MyDrive/Bangla_Smishing_Project/notebooks -> True
/content/drive/MyDrive/Bangla_Smishing_Project/models -> True
/content/drive/MyDrive/Bangla_Smishing_Project/outputs -> True
/content/drive/MyDrive/Bangla_Smishing_Project/results -> True

In [17]:
!pip install -q git+https://github.com/csebuetnlp/normalizer

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.0/185.0 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 6.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for normalizer (setup.py) ... done
  Building wheel for emoji (setup.py) ... done
  Building wheel for ftfy (setup.py) ... done

In [18]:
!pip install -q shap lime

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for lime (setup.py) ... done

In [19]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn
import torch
import transformers
import datasets
import accelerate
import shap
import lime

print("===== ENVIRONMENT CHECK =====")

print("Pandas       :", pd.__version__)
print("NumPy        :", np.__version__)
print("Scikit-learn :", sklearn.__version__)
print("Matplotlib   :", matplotlib.__version__)
print("Seaborn      :", seaborn.__version__)
print("PyTorch      :", torch.__version__)
print("Transformers :", transformers.__version__)
print("Datasets     :", datasets.__version__)
print("Accelerate   :", accelerate.__version__)
print("SHAP         :", shap.__version__)
print("LIME         : Installed")

print("\nEnvironment check complete ✅")

===== ENVIRONMENT CHECK =====
Pandas       : 2.2.3
NumPy        : 2.1.3
Scikit-learn : 1.6.1
Matplotlib   : 3.10.0
Seaborn      : 0.13.2
PyTorch      : 2.11.0+cu128
Transformers : 5.15.1
Datasets     : 4.0.0
Accelerate   : 1.14.0
SHAP         : 0.52.0
LIME         : Installed

Environment check complete ✅

In [20]:
from normalizer import normalize

sample_text = "আপনার অ্যাকাউন্ট এখনই verify করুন।"

normalized_text = normalize(sample_text)

print("Original:")
print(sample_text)

print("\nNormalized:")
print(normalized_text)

Original:
আপনার অ্যাকাউন্ট এখনই verify করুন।

Normalized:
আপনার অ্যাকাউন্ট এখনই verify করুন।

In [21]:
MODEL_NAME = "csebuetnlp/banglabert"

print("Model:", MODEL_NAME)

Model: csebuetnlp/banglabert

In [22]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("✅ BanglaBERT tokenizer loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/586 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/528k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

✅ BanglaBERT tokenizer loaded

In [23]:
sample_text = "আপনার বিকাশ অ্যাকাউন্ট যাচাই করুন এখনই।"

sample_text = normalize(sample_text)

tokens = tokenizer.tokenize(sample_text)

print("Tokens:")
print(tokens)

Tokens:
['আপনার', 'বিকাশ', 'অ্যাকাউন্ট', 'যাচাই', 'করুন', 'এখনই', '।']

In [24]:
encoded = tokenizer(
    sample_text,
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

print("Input IDs shape:", encoded["input_ids"].shape)
print("Attention mask shape:", encoded["attention_mask"].shape)

Input IDs shape: torch.Size([1, 9])
Attention mask shape: torch.Size([1, 9])

In [25]:
from transformers import AutoModel

MODEL_NAME = "csebuetnlp/banglabert" # Added this line to define MODEL_NAME
banglabert = AutoModel.from_pretrained(MODEL_NAME)

print("✅ BanglaBERT backbone loaded")

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  443MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] ElectraModel LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |  |
--------------------------------------------------+------------+--+-
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |  |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |  |
discriminator_predictions.dense.weight            | UNEXPECTED |  |
discriminator_predictions.dense.bias              | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

✅ BanglaBERT backbone loaded

In [26]:
print("Hidden size:", banglabert.config.hidden_size)
print("Number of layers:", banglabert.config.num_hidden_layers)
print("Max position:", banglabert.config.max_position_embeddings)

Hidden size: 768
Number of layers: 12
Max position: 512

In [27]:
import torch

In [28]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

banglabert = banglabert.to(device)

print("Using device:", device)

Using device: cuda

In [29]:
!pip install -q git+https://github.com/csebuetnlp/normalizer.git

  Preparing metadata (setup.py) ... done

In [30]:
from normalizer import normalize

print("✅ Normalizer imported successfully!")

✅ Normalizer imported successfully!

In [31]:
import torch
from normalizer import normalize
from transformers import AutoTokenizer, AutoModel

In [32]:
MODEL_NAME = "csebuetnlp/banglabert"

print(MODEL_NAME)

csebuetnlp/banglabert

In [33]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("✅ Tokenizer loaded successfully")

✅ Tokenizer loaded successfully

In [34]:
banglabert = AutoModel.from_pretrained(MODEL_NAME)

print("✅ BanglaBERT loaded successfully")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] ElectraModel LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |  |
--------------------------------------------------+------------+--+-
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |  |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |  |
discriminator_predictions.dense.weight            | UNEXPECTED |  |
discriminator_predictions.dense.bias              | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

✅ BanglaBERT loaded successfully

In [35]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

banglabert = banglabert.to(device)

print("Using device:", device)

Using device: cuda

In [36]:
sample_text = "আপনার অ্যাকাউন্ট বন্ধ হয়ে যাবে। এখনই যাচাই করুন।"

sample_text = normalize(sample_text)

inputs = tokenizer(
    sample_text,
    return_tensors="pt",
    truncation=True,
    max_length=128
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

with torch.no_grad():
    outputs = banglabert(**inputs)

print("✅ SMS successfully processed")
print("Output shape:", outputs.last_hidden_state.shape)

✅ SMS successfully processed
Output shape: torch.Size([1, 12, 768])

In [37]:
import pandas as pd

df = pd.read_csv(CSV_PATH)

print("Dataset loaded ✅")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded ✅
Rows: 1253
Columns: 33

In [38]:
print(df.columns.tolist())

['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1']

In [39]:
print(df.dtypes)

label                 object
text                  object
source                object
has_url                int64
label_id               int64
text_original         object
text_normalized       object
urls                  object
url_count              int64
url_count.1            int64
url_total_length       int64
url_max_length         int64
url_digit_count        int64
url_dot_count          int64
url_hyphen_count       int64
url_slash_count        int64
url_has_https          int64
url_has_ip             int64
url_has_at             int64
url_is_shortened       int64
text_for_model        object
character_length       int64
url_count.2            int64
url_total_length.1     int64
url_max_length.1       int64
url_digit_count.1      int64
url_dot_count.1        int64
url_hyphen_count.1     int64
url_slash_count.1      int64
url_has_https.1        int64
url_has_ip.1           int64
url_has_at.1           int64
url_is_shortened.1     int64
dtype: object

In [40]:
print(df.isnull().sum())

label                 0
text                  0
source                0
has_url               0
label_id              0
text_original         0
text_normalized       0
urls                  0
url_count             0
url_count.1           0
url_total_length      0
url_max_length        0
url_digit_count       0
url_dot_count         0
url_hyphen_count      0
url_slash_count       0
url_has_https         0
url_has_ip            0
url_has_at            0
url_is_shortened      0
text_for_model        0
character_length      0
url_count.2           0
url_total_length.1    0
url_max_length.1      0
url_digit_count.1     0
url_dot_count.1       0
url_hyphen_count.1    0
url_slash_count.1     0
url_has_https.1       0
url_has_ip.1          0
url_has_at.1          0
url_is_shortened.1    0
dtype: int64

In [41]:
print(df["label"].value_counts())

label
smish     495
normal    451
promo     307
Name: count, dtype: int64

In [42]:
class_percent = (
    df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(class_percent)

label
smish     39.51
normal    35.99
promo     24.50
Name: proportion, dtype: float64

In [43]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate texts:", df["text"].duplicated().sum())

Duplicate rows: 0
Duplicate texts: 0

In [44]:
empty_text = df["text"].astype(str).str.strip().eq("").sum()

print("Empty SMS messages:", empty_text)

Empty SMS messages: 0

In [45]:
display(df.head(10))

,label,text,source,has_url,label_id,text_original,text_normalized,urls,url_count,url_count.1,...,url_total_length.1,url_max_length.1,url_digit_count.1,url_dot_count.1,url_hyphen_count.1,url_slash_count.1,url_has_https.1,url_has_ip.1,url_has_at.1,url_is_shortened.1
0,smish,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...,Bengali,1,2,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...,['winlottery.tk/claim'],1,1,...,19,19,0,1,0,1,0,0,0,0
1,smish,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...,Bengali,1,2,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...,['https://wa.me/8801917788990'],1,1,...,27,27,13,1,0,3,1,0,0,0
2,smish,জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...,Bengali,0,2,জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...,জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...,[],0,0,...,0,0,0,0,0,0,0,0,0,0
3,normal,ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...,Bengali,0,0,ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...,ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভা...,[],0,0,...,0,0,0,0,0,0,0,0,0,0
4,promo,"স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...",Bengali,0,1,"স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...","স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...",[],0,0,...,0,0,0,0,0,0,0,0,0,0
5,smish,জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...,Bengali,0,2,জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...,জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...,[],0,0,...,0,0,0,0,0,0,0,0,0,0
6,smish,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...,Bengali,1,2,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...,['student-loan.tk'],1,1,...,15,15,0,1,1,0,0,0,0,0
7,smish,"আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...",Bengali,1,2,"আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...","আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...",['bit.ly/AccountUpdateBD'],1,1,...,22,22,0,1,0,1,0,0,0,1
8,promo,পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...,Bengali,0,1,পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...,পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...,[],0,0,...,0,0,0,0,0,0,0,0,0,0
9,promo,Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...,Bengali,0,1,Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...,Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...,[],0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
for label in sorted(df["label"].unique()):
    print("\n" + "=" * 70)
    print("CLASS:", label)
    print("=" * 70)

    examples = df[df["label"] == label]["text"].head(3)

    for i, message in enumerate(examples, 1):
        print(f"{i}. {message}")

======================================================================
CLASS: normal
======================================================================
1. ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব খাটিয়ে ব্যবসায়ী হওয়া বড় অপরাধ। কারণ এই ব্যবসায়ীদের অর্জিত অর্থের বেশিরভাগই আসে সাধারণ মানুষের রক্তচোষা টাকা থেকে। — রেদোয়ান মাসুদ
2. আম্মু, আমার পরীক্ষার রেজাল্ট কাল বের হবে। দোয়া করবেন।
3. আজকে নতুন রেস্টুরেন্টে খেতে গিয়েছিলাম। খাবারের স্বাদ বেশ ভালো, দামও খুব বেশি না। ভাবছি আবারও যাবো।

======================================================================
CLASS: promo
======================================================================
1. স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ছাড়।
2. পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯ টাকা মাত্র।
3. Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ টাকায় পাবেন। বৈধতা ৩ দিন।

======================================================================
CLASS: smish
======================================================================
1. জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim করতে: winlottery.tk/claim পূরণ করুন।
2. বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্তারিত জানতে এখানে ক্লিক করুন: https://wa.me/8801917788990
3. জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চালু করতে কল করুন: +8801815566778

In [47]:
import re

URL_PATTERN = r'https?://\S+|www\.\S+|(?:bit\.ly|tinyurl\.com|cutt\.ly)/\S+'

df["has_url"] = df["text"].astype(str).str.contains(
    URL_PATTERN,
    case=False,
    regex=True
)

print(df["has_url"].value_counts())

has_url
False    1056
True      197
Name: count, dtype: int64

In [48]:
url_by_class = pd.crosstab(
    df["label"],
    df["has_url"]
)

print(url_by_class)

has_url  False  True
label
normal     447      4
promo      220     87
smish      389    106

In [49]:
# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = (
    "Explainable Multiclass Bangla Smishing Detection "
    "Using BanglaBERT and URL Feature Fusion"
)

MODEL_NAME = "csebuetnlp/banglabert"

TEXT_COLUMN = "text"
TARGET_COLUMN = "label"

LABELS = [
    "normal",
    "promo",
    "smish"
]

NUM_LABELS = len(LABELS)

MAX_LENGTH = 128
SEED = 42

print("Project:", PROJECT_NAME)
print("Model:", MODEL_NAME)
print("Labels:", LABELS)
print("Number of labels:", NUM_LABELS)
print("Max text length:", MAX_LENGTH)

Project: Explainable Multiclass Bangla Smishing Detection Using BanglaBERT and URL Feature Fusion
Model: csebuetnlp/banglabert
Labels: ['normal', 'promo', 'smish']
Number of labels: 3
Max text length: 128

In [50]:
import random
import numpy as np
import torch

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("✅ Random seed:", SEED)

✅ Random seed: 42

In [51]:
directories = [
    DATA_DIR,
    MODEL_DIR,
    OUTPUT_DIR,
    RESULTS_DIR,
    os.path.join(OUTPUT_DIR, "figures"),
    os.path.join(OUTPUT_DIR, "confusion_matrices"),
    os.path.join(OUTPUT_DIR, "predictions"),
]

for directory in directories:
    os.makedirs(directory, exist_ok=True)

print("✅ All project directories are ready")

✅ All project directories are ready

In [52]:
dataset_info = {
    "rows": int(df.shape[0]),
    "columns": int(df.shape[1]),
    "columns_list": df.columns.tolist(),
    "labels": df["label"].value_counts().to_dict(),
    "missing_values": df.isnull().sum().to_dict()
}

print(dataset_info)

{'rows': 1253, 'columns': 33, 'columns_list': ['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1'], 'labels': {'smish': 495, 'normal': 451, 'promo': 307}, 'missing_values': {'label': 0, 'text': 0, 'source': 0, 'has_url': 0, 'label_id': 0, 'text_original': 0, 'text_normalized': 0, 'urls': 0, 'url_count': 0, 'url_count.1': 0, 'url_total_length': 0, 'url_max_length': 0, 'url_digit_count': 0, 'url_dot_count': 0, 'url_hyphen_count': 0, 'url_slash_count': 0, 'url_has_https': 0, 'url_has_ip': 0, 'url_has_at': 0, 'url_is_shortened': 0, 'text_for_model': 0, 'character_length': 0, 'url_count.2': 0, 'url_total_length.1': 0, 'url_max_length.1': 0, 'url_digit_count.1': 0, 'url_dot_count.1': 0, 'url_hyphen_count.1': 0, 'url_slash_count.1': 0, 'url_has_https.1': 0, 'url_has_ip.1': 0, 'url_has_at.1': 0, 'url_is_shortened.1': 0}}

In [53]:
import sys
import json

environment_info = {
    "python": sys.version,
    "pandas": pd.__version__,
    "numpy": np.__version__,
    "torch": torch.__version__,
    "transformers": transformers.__version__,
    "datasets": datasets.__version__,
    "accelerate": accelerate.__version__,
    "sklearn": sklearn.__version__,
    "cuda_available": torch.cuda.is_available(),
    "gpu": torch.cuda.get_device_name(0)
        if torch.cuda.is_available()
        else None
}

env_path = os.path.join(RESULTS_DIR, "environment_info.json")

with open(env_path, "w") as f:
    json.dump(environment_info, f, indent=4)

print("✅ Environment information saved to:")
print(env_path)

✅ Environment information saved to:
/content/drive/MyDrive/Bangla_Smishing_Project/results/environment_info.json

In [54]:
print("=" * 60)
print("FINAL SETUP CHECK")
print("=" * 60)

checks = {
    "GPU available": torch.cuda.is_available(),
    "CSV exists": os.path.exists(CSV_PATH),
    "Dataset loaded": "df" in globals(),
    "BanglaBERT tokenizer": "tokenizer" in globals(),
    "BanglaBERT model": "banglabert" in globals(),
    "Normalizer available": "normalize" in globals(),
    "SHAP installed": "shap" in globals(),
    "Project folder exists": os.path.exists(PROJECT_DIR),
}

for item, status in checks.items():
    print(f"{'✅' if status else '❌'} {item}")

print("=" * 60)

============================================================
FINAL SETUP CHECK
============================================================
✅ GPU available
✅ CSV exists
✅ Dataset loaded
✅ BanglaBERT tokenizer
✅ BanglaBERT model
✅ Normalizer available
✅ SHAP installed
✅ Project folder exists
============================================================

In [55]:

import os
import re
import pandas as pd
import numpy as np

from normalizer import normalize

print("✅ Preprocessing libraries imported successfully")

✅ Preprocessing libraries imported successfully

In [56]:
df_raw = df.copy()

print("Original dataset shape:", df_raw.shape)
print("Original columns:", df_raw.columns.tolist())

Original dataset shape: (1253, 33)
Original columns: ['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1']

In [57]:
required_columns = ["label", "text", "source"]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"❌ Missing required columns: {missing_columns}"
    )

print("✅ All required columns are present")

✅ All required columns are present

In [58]:
print("Missing values:")
print(df[required_columns].isnull().sum())

Missing values:
label     0
text      0
source    0
dtype: int64

In [59]:
before_rows = len(df)

df = df.dropna(subset=["text", "label"]).copy()

after_rows = len(df)

print("Rows before:", before_rows)
print("Rows after :", after_rows)
print("Rows removed:", before_rows - after_rows)

Rows before: 1253
Rows after : 1253
Rows removed: 0

In [60]:
df["text"] = df["text"].astype(str)
df["label"] = df["label"].astype(str)

print(df[["text", "label"]].dtypes)

text     object
label    object
dtype: object

In [61]:
df["text"] = df["text"].str.strip()

print("✅ Leading/trailing whitespace cleaned")

✅ Leading/trailing whitespace cleaned

In [62]:
duplicate_count = df["text"].duplicated().sum()

print("Duplicate SMS messages:", duplicate_count)

Duplicate SMS messages: 0

In [63]:
before_rows = len(df)

df = df.drop_duplicates(
    subset=["text"],
    keep="first"
).reset_index(drop=True)

after_rows = len(df)

print("Rows before duplicate removal:", before_rows)
print("Rows after duplicate removal :", after_rows)
print("Duplicates removed:", before_rows - after_rows)

Rows before duplicate removal: 1253
Rows after duplicate removal : 1253
Duplicates removed: 0

In [64]:
print(df["label"].value_counts())

label
smish     495
normal    451
promo     307
Name: count, dtype: int64

In [65]:
df["label"] = (
    df["label"]
    .str.strip()
    .str.lower()
)

print(df["label"].value_counts())

label
smish     495
normal    451
promo     307
Name: count, dtype: int64

In [66]:
expected_labels = {"normal", "promo", "smish"}

actual_labels = set(df["label"].unique())

print("Actual labels:", actual_labels)

if actual_labels != expected_labels:
    raise ValueError(
        f"Unexpected labels found.\n"
        f"Expected: {expected_labels}\n"
        f"Found: {actual_labels}"
    )

print("✅ Labels are correct")

Actual labels: {'promo', 'normal', 'smish'}
✅ Labels are correct

In [67]:
label2id = {
    "normal": 0,
    "promo": 1,
    "smish": 2
}

id2label = {
    0: "normal",
    1: "promo",
    2: "smish"
}

df["label_id"] = df["label"].map(label2id)

print(df[["label", "label_id"]].head(10))

    label  label_id
0   smish         2
1   smish         2
2   smish         2
3  normal         0
4   promo         1
5   smish         2
6   smish         2
7   smish         2
8   promo         1
9   promo         1

In [68]:
print(df["label_id"].value_counts().sort_index())

label_id
0    451
1    307
2    495
Name: count, dtype: int64

In [69]:
df["text_original"] = df["text"]

print(df[["text_original", "label"]].head())

                                       text_original   label
0  জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...   smish
1  বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...   smish
2  জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...   smish
3  ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...  normal
4  স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...   promo

In [70]:
def normalize_text(text):
    try:
        text = str(text).strip()
        return normalize(text)
    except Exception:
        return str(text).strip()

In [71]:
test_text = df.loc[0, "text_original"]

print("Original:")
print(test_text)

print("\nNormalized:")
print(normalize_text(test_text))

Original:
জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim করতে: winlottery.tk/claim পূরণ করুন।

Normalized:
জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim করতে: winlottery.tk/claim পূরণ করুন।

In [72]:
df["text_normalized"] = df["text_original"].apply(normalize_text)

print("✅ Text normalization completed")

✅ Text normalization completed

In [73]:
comparison = df[
    ["text_original", "text_normalized"]
].head(10)

display(comparison)

,text_original,text_normalized
0,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
2,জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...,জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...
3,ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...,ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভা...
4,"স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...","স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ..."
5,জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...,জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...
6,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7,"আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...","আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে..."
8,পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...,পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...
9,Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...,Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...

In [74]:
URL_PATTERN = re.compile(
    r"""
    (?:
        https?://
    )?
    (?:
        www\.
        |
        (?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,}
    )
    (?::\d+)?
    (?:/[^\s\]\[<>"']*)?
    """,
    re.IGNORECASE | re.VERBOSE
)

In [75]:
def extract_urls(text):
    text = str(text)
    urls = URL_PATTERN.findall(text)
    return urls

In [76]:
for i in range(min(10, len(df))):
    text = df.loc[i, "text_original"]
    urls = extract_urls(text)

    if urls:
        print("SMS:")
        print(text)
        print("URLs:", urls)
        print("-" * 70)

SMS:
জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim করতে: winlottery.tk/claim পূরণ করুন।
URLs: ['winlottery.tk/claim']
----------------------------------------------------------------------
SMS:
বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্তারিত জানতে এখানে ক্লিক করুন: https://wa.me/8801917788990
URLs: ['https://wa.me/8801917788990']
----------------------------------------------------------------------
SMS:
আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্টিভেট: student-loan.tk
URLs: ['student-loan.tk']
----------------------------------------------------------------------
SMS:
আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে এটি বন্ধ হয়ে যাবে। লিঙ্কে ক্লিক করুন: [bit.ly/AccountUpdateBD]
URLs: ['bit.ly/AccountUpdateBD']
----------------------------------------------------------------------

In [77]:
df["urls"] = df["text_original"].apply(extract_urls)

print(df[["text_original", "urls"]].head(10))

                                       text_original  \
0  জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1  বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
2  জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...
3  ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...
4  স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...
5  জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...
6  আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7  আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...
8  পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...
9  Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...

                            urls
0          [winlottery.tk/claim]
1  [https://wa.me/8801917788990]
2                             []
3                             []
4                             []
5                             []
6              [student-loan.tk]
7       [bit.ly/AccountUpdateBD]
8                             []
9                             []

In [78]:
df["url_count"] = df["urls"].apply(len)

print(df["url_count"].value_counts().sort_index())

url_count
0    845
1    392
2     16
Name: count, dtype: int64

In [79]:
df["has_url"] = (df["url_count"] > 0).astype(int)

print(df["has_url"].value_counts())

has_url
0    845
1    408
Name: count, dtype: int64

In [80]:
url_distribution = pd.crosstab(
    df["label"],
    df["has_url"]
)

print(url_distribution)

has_url    0    1
label
normal   447    4
promo    207  100
smish    191  304

In [81]:
def extract_url_features(urls):
    if not urls:
        return {
            "url_count": 0,
            "url_total_length": 0,
            "url_max_length": 0,
            "url_digit_count": 0,
            "url_dot_count": 0,
            "url_hyphen_count": 0,
            "url_slash_count": 0,
            "url_has_https": 0,
            "url_has_ip": 0,
            "url_has_at": 0,
            "url_is_shortened": 0
        }

    urls = [str(url) for url in urls]

    total_length = sum(len(url) for url in urls)
    max_length = max(len(url) for url in urls)

    digit_count = sum(
        sum(char.isdigit() for char in url)
        for url in urls
    )

    dot_count = sum(url.count(".") for url in urls)

    hyphen_count = sum(
        url.count("-")
        for url in urls
    )

    slash_count = sum(
        url.count("/")
        for url in urls
    )

    has_https = int(
        any(url.lower().startswith("https://") for url in urls)
    )

    ip_pattern = re.compile(
        r"(?:\d{1,3}\.){3}\d{1,3}"
    )

    has_ip = int(
        any(ip_pattern.search(url) for url in urls)
    )

    has_at = int(
        any("@" in url for url in urls)
    )

    shortened_domains = [
        "bit.ly",
        "tinyurl.com",
        "t.co",
        "cutt.ly",
        "goo.gl",
        "is.gd",
        "ow.ly",
        "shorturl.at"
    ]

    is_shortened = int(
        any(
            domain in url.lower()
            for url in urls
            for domain in shortened_domains
        )
    )

    return {
        "url_count": len(urls),
        "url_total_length": total_length,
        "url_max_length": max_length,
        "url_digit_count": digit_count,
        "url_dot_count": dot_count,
        "url_hyphen_count": hyphen_count,
        "url_slash_count": slash_count,
        "url_has_https": has_https,
        "url_has_ip": has_ip,
        "url_has_at": has_at,
        "url_is_shortened": is_shortened
    }

In [82]:
test_urls = df.loc[0, "urls"]

print("URLs:", test_urls)

print("\nExtracted URL features:")
print(extract_url_features(test_urls))

URLs: ['winlottery.tk/claim']

Extracted URL features:
{'url_count': 1, 'url_total_length': 19, 'url_max_length': 19, 'url_digit_count': 0, 'url_dot_count': 1, 'url_hyphen_count': 0, 'url_slash_count': 1, 'url_has_https': 0, 'url_has_ip': 0, 'url_has_at': 0, 'url_is_shortened': 0}

In [83]:
url_features = df["urls"].apply(extract_url_features)

url_features_df = pd.DataFrame(
    url_features.tolist(),
    index=df.index
)

print(url_features_df.head())

   url_count  url_total_length  url_max_length  url_digit_count  \
0          1                19              19                0
1          1                27              27               13
2          0                 0               0                0
3          0                 0               0                0
4          0                 0               0                0

   url_dot_count  url_hyphen_count  url_slash_count  url_has_https  \
0              1                 0                1              0
1              1                 0                3              1
2              0                 0                0              0
3              0                 0                0              0
4              0                 0                0              0

   url_has_ip  url_has_at  url_is_shortened
0           0           0                 0
1           0           0                 0
2           0           0                 0
3           0           0                 0
4           0           0                 0

In [84]:
df = pd.concat(
    [df, url_features_df],
    axis=1
)

print("✅ URL features added")
print(df.columns.tolist())

✅ URL features added
['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1', 'url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened']

In [85]:
print(
    df[url_features_df.columns].dtypes
)

url_count           int64
url_count           int64
url_total_length    int64
url_total_length    int64
url_max_length      int64
url_max_length      int64
url_digit_count     int64
url_digit_count     int64
url_dot_count       int64
url_dot_count       int64
url_hyphen_count    int64
url_hyphen_count    int64
url_slash_count     int64
url_slash_count     int64
url_has_https       int64
url_has_https       int64
url_has_ip          int64
url_has_ip          int64
url_has_at          int64
url_has_at          int64
url_is_shortened    int64
url_is_shortened    int64
dtype: object

In [86]:
display(
    df[
        [
            "label",
            "url_count",
            "url_total_length",
            "url_max_length",
            "url_digit_count",
            "url_dot_count",
            "url_hyphen_count",
            "url_slash_count",
            "url_has_https",
            "url_has_ip",
            "url_has_at",
            "url_is_shortened"
        ]
    ].head(15)
)

,label,url_count,url_count,url_total_length,url_total_length,url_max_length,url_max_length,url_digit_count,url_digit_count,url_dot_count,...,url_slash_count,url_slash_count,url_has_https,url_has_https,url_has_ip,url_has_ip,url_has_at,url_has_at,url_is_shortened,url_is_shortened
0,smish,1,1,19,19,19,19,0,0,1,...,1,1,0,0,0,0,0,0,0,0
1,smish,1,1,27,27,27,27,13,13,1,...,3,3,1,1,0,0,0,0,0,0
2,smish,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,normal,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,promo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,smish,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,smish,1,1,15,15,15,15,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,smish,1,1,22,22,22,22,0,0,1,...,1,1,0,0,0,0,0,0,1,1
8,promo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,promo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,smish,1,1,25,25,25,25,0,0,1,...,1,1,0,0,0,0,0,0,0,0
11,smish,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,smish,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,smish,2,2,20,20,16,16,3,3,2,...,0,0,0,0,0,0,0,0,0,0
14,normal,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
def replace_urls_with_token(text):
    text = str(text)
    return URL_PATTERN.sub(" [URL] ", text)

In [88]:
df["text_for_model"] = df["text_normalized"].apply(
    replace_urls_with_token
)

print(df[
    [
        "text_original",
        "text_normalized",
        "text_for_model"
    ]
].head(10))

                                       text_original  \
0  জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1  বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
2  জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...
3  ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভাব ...
4  স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...
5  জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...
6  আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7  আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...
8  পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...
9  Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...

                                     text_normalized  \
0  জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1  বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
2  জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...
3  ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভা...
4  স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...
5  জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...
6  আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7  আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...
8  পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...
9  Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...

                                      text_for_model
0  জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1  বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
2  জনতা ব্যাংক অ্যাকাউন্ট ব্লক হয়েছে। পুনরায় চা...
3  ব্যবসায়ী হওয়া অপরাধ না কিন্তু রাজনৈতিক প্রভা...
4  স্টেশনারিতে মেগা সেল! কলম, নোটবুক, ব্যাগে ৩৫% ...
5  জয়ধ্বনি! আপনার নাম সরকারি লটারিতে এসেছে। ৫০ ল...
6  আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7  আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...
8  পিজা হাটে কম্বো অফার! ২টি পিজা + ২টি কোক = ৭৯৯...
9  Banglalink গ্রাহকরা শুক্রবার ৪ জিবি মাত্র ৭৯ ট...

In [89]:
url_rows = df[df["has_url"] == 1]

print("Number of SMS with URLs:", len(url_rows))

if len(url_rows) > 0:
    display(
        url_rows[
            [
                "text_original",
                "text_for_model"
            ]
        ].head(10)
    )

Number of SMS with URLs: 408

,text_original,text_for_model
0,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...,জয়! আপনি Google লটারিতে $৫০০০০ জিতেছেন। claim...
1,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...,বাংলাদেশ ব্যাংক থেকে গুরুত্বপূর্ণ বার্তা। বিস্...
6,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...,আপনার স্টুডেন্ট লোন একাউন্ট সাসপেন্ড। রিঅ্যাক্...
7,"আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে...","আপনার অ্যাকাউন্টটি অবিলম্বে আপডেট করুন, না হলে..."
10,আপনার মোবাইল নম্বর যাচাই করতে এখানে ক্লিক করুন...,আপনার মোবাইল নম্বর যাচাই করতে এখানে ক্লিক করুন...
13,"অভিনন্দন!! দারাজ থেকে BDT 5,000 গিফট ভাউচার পা...","অভিনন্দন!! দারাজ থেকে BDT 5,000 গিফট ভাউচার পা..."
15,ঈদ উপলয়ে ব্রাক ব্যাংক সবার বিকাশ একাউন্টে ১০০...,ঈদ উপলয়ে ব্রাক ব্যাংক সবার বিকাশ একাউন্টে ১০০...
18,সোনালী ব্যাংক অ্যাকাউন্টে ত্রুটি দেখা দিয়েছে।...,সোনালী ব্যাংক অ্যাকাউন্টে ত্রুটি দেখা দিয়েছে।...
20,বাংলাদেশ ব্যাংক অ্যাকাউন্ট আপডেট করতে এখানে ক্...,বাংলাদেশ ব্যাংক অ্যাকাউন্ট আপডেট করতে এখানে ক্...
28,শাকিবের সাথে লাঞ্চ করার সুযোগ পেতে আজই আইপিএলে...,শাকিবের সাথে লাঞ্চ করার সুযোগ পেতে আজই আইপিএলে...

In [90]:
df["character_length"] = df["text_for_model"].str.len()

print(df["character_length"].describe())

count    1253.00000
mean       78.56265
std        58.96795
min         4.00000
25%        50.00000
50%        65.00000
75%        89.00000
max       555.00000
Name: character_length, dtype: float64

In [91]:
long_messages = df.sort_values(
    "character_length",
    ascending=False
).head(10)

display(
    long_messages[
        [
            "label",
            "character_length",
            "text_for_model"
        ]
    ]
)

,label,character_length,text_for_model
1037,smish,555,ঘরে বসে অনেক ভাবে ইনকাম করা যায়। যেমন কেউ ইউট...
761,smish,525,"হ্যালো, আমার নাম আলিয়ে। আপনাকে বিরক্ত করার জন..."
452,smish,484,"প্রিয় প্রার্থী, আপনি বাছাই করা হয়েছে ব্র্যাক..."
788,smish,455,"PLC,LIMITED. প্রিয় আবেদনকারী, অভিনন্দন! আপনার..."
912,promo,448,নতুন বছরের মেগা সেল এসেছে বসুন্ধরা সিটি শপিং ম...
353,smish,416,বিশেষ জরুরি ঘোষণা! আপনার নামে একটি বড় আর্থিক ...
786,promo,401,এয়ারটেলের বিপ্লবী অফার - 'স্মার্ট স্টুডেন্ট প...
491,normal,393,"আমার প্রিয় বন্ধু রাকিব, তোমার বিয়ের দাওয়াত ..."
960,normal,390,"প্রিয় আম্মু, আমি এতক্ষণ হাসপাতালে ছিলাম বাবার..."
568,normal,377,"প্রিয় বোন সুমি, তোমার পরীক্ষার ফলাফল নিয়ে আম..."

In [92]:
empty_model_text = (
    df["text_for_model"]
    .str.strip()
    .eq("")
    .sum()
)

print("Empty model texts:", empty_model_text)

Empty model texts: 0

In [93]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nLabels:")
print(df["label"].value_counts())

print("\nMissing values:")
print(
    df[
        [
            "label",
            "text_original",
            "text_normalized",
            "text_for_model"
        ]
    ].isnull().sum()
)

Dataset shape: (1253, 44)

Columns:
['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1', 'url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened']

Labels:
label
smish     495
normal    451
promo     307
Name: count, dtype: int64

Missing values:
label              0
text_original      0
text_normalized    0
text_for_model     0
dtype: int64

In [94]:
label_consistency = (
    df.groupby("text_original")["label"]
    .nunique()
)

problematic_texts = label_consistency[
    label_consistency > 1
]

print(
    "SMS texts with conflicting labels:",
    len(problematic_texts)
)

SMS texts with conflicting labels: 0

In [95]:
PREPROCESSED_PATH = os.path.join(
    DATA_DIR,
    "bangla_smishing_preprocessed.csv"
)

df.to_csv(
    PREPROCESSED_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Preprocessed dataset saved:")
print(PREPROCESSED_PATH)

✅ Preprocessed dataset saved:
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/bangla_smishing_preprocessed.csv

In [96]:
if os.path.exists(PREPROCESSED_PATH):
    print("✅ Preprocessed CSV exists")
    print(
        "File size:",
        round(
            os.path.getsize(PREPROCESSED_PATH) / 1024,
            2
        ),
        "KB"
    )
else:
    print("❌ File was not saved")

✅ Preprocessed CSV exists
File size: 1114.77 KB

In [97]:
df_check = pd.read_csv(
    PREPROCESSED_PATH
)

print("Reloaded shape:", df_check.shape)
print("Reloaded columns:")
print(df_check.columns.tolist())

Reloaded shape: (1253, 44)
Reloaded columns:
['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1', 'url_count.3', 'url_total_length.2', 'url_max_length.2', 'url_digit_count.2', 'url_dot_count.2', 'url_hyphen_count.2', 'url_slash_count.2', 'url_has_https.2', 'url_has_ip.2', 'url_has_at.2', 'url_is_shortened.2']

In [98]:
URL_FEATURE_COLUMNS = [
    "url_count",
    "url_total_length",
    "url_max_length",
    "url_digit_count",
    "url_dot_count",
    "url_hyphen_count",
    "url_slash_count",
    "url_has_https",
    "url_has_ip",
    "url_has_at",
    "url_is_shortened"
]

print("URL features:")
for feature in URL_FEATURE_COLUMNS:
    print("-", feature)

URL features:
- url_count
- url_total_length
- url_max_length
- url_digit_count
- url_dot_count
- url_hyphen_count
- url_slash_count
- url_has_https
- url_has_ip
- url_has_at
- url_is_shortened

In [99]:
missing_url_features = [
    feature
    for feature in URL_FEATURE_COLUMNS
    if feature not in df.columns
]

if missing_url_features:
    raise ValueError(
        f"Missing URL features: {missing_url_features}"
    )

print("✅ All URL features are present")

✅ All URL features are present

In [100]:
print("=" * 70)
print("PREPROCESSING SUMMARY")
print("=" * 70)

print("Total SMS:", len(df))
print("Classes:", df["label"].unique().tolist())

print("\nClass distribution:")
print(df["label"].value_counts())

print("\nURL statistics:")
print("SMS with URL:", int(df["has_url"].sum()))
print(
    "SMS without URL:",
    int((df["has_url"] == 0).sum())
)

print("\nText columns:")
print("- text_original")
print("- text_normalized")
print("- text_for_model")

print("\nURL feature count:", len(URL_FEATURE_COLUMNS))

print("\nSaved file:")
print(PREPROCESSED_PATH)

print("=" * 70)
print("✅ PREPROCESSING COMPLETED")
print("=" * 70)

======================================================================
PREPROCESSING SUMMARY
======================================================================
Total SMS: 1253
Classes: ['smish', 'normal', 'promo']

Class distribution:
label
smish     495
normal    451
promo     307
Name: count, dtype: int64

URL statistics:
SMS with URL: 408
SMS without URL: 845

Text columns:
- text_original
- text_normalized
- text_for_model

URL feature count: 11

Saved file:
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/bangla_smishing_preprocessed.csv
======================================================================
✅ PREPROCESSING COMPLETED
======================================================================

### **# 14. Additional Text and Structured Features**

In [101]:
import unicodedata

def unicode_nfc(text):
    return unicodedata.normalize(
        "NFC",
        str(text)
    )

df["text_unicode"] = df["text_original"].apply(
    unicode_nfc
)

print("✅ Unicode NFC normalization completed")

✅ Unicode NFC normalization completed

In [102]:
def clean_whitespace(text):
    text = str(text)

    # Replace newlines, tabs, and repeated spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

df["text_clean"] = df["text_unicode"].apply(
    clean_whitespace
)

print("✅ Whitespace normalization completed")

✅ Whitespace normalization completed

In [103]:
df["text_normalized"] = df["text_clean"].apply(
    normalize_text
)

print("✅ BanglaBERT-compatible normalization completed")

✅ BanglaBERT-compatible normalization completed

In [104]:
df["text_for_model"] = df["text_normalized"].apply(
    replace_urls_with_token
)

print("✅ Model text updated")

✅ Model text updated

In [105]:
print("Unique source values:")
print(df["source"].value_counts())

print("\nNumber of unique sources:")
print(df["source"].nunique())

Unique source values:
source
Bengali    1253
Name: count, dtype: int64

Number of unique sources:
1

# **source × label**

In [106]:
source_label_table = pd.crosstab(
    df["source"],
    df["label"]
)

display(source_label_table)

label    normal  promo  smish
source
Bengali     451    307    495

# **Phone-number features**

In [107]:
PHONE_PATTERN = re.compile(
    r"(?<!\d)(?:\+?88)?01[3-9]\d{8}(?!\d)"
)

def extract_phone_features(text):
    text = str(text)

    phones = PHONE_PATTERN.findall(text)

    return {
        "phone_count": len(phones),
        "has_phone": int(len(phones) > 0)
    }

In [108]:
phone_features = df["text_clean"].apply(
    extract_phone_features
)

phone_features_df = pd.DataFrame(
    phone_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, phone_features_df],
    axis=1
)

print("✅ Phone features added")

✅ Phone features added

# **Number/digit features**

In [109]:
def extract_number_features(text):
    text = str(text)

    digits = re.findall(r"\d", text)
    numbers = re.findall(r"\d+(?:[.,]\d+)?", text)

    return {
        "digit_count": len(digits),
        "number_count": len(numbers),
        "has_digits": int(len(digits) > 0)
    }

In [110]:
number_features = df["text_clean"].apply(
    extract_number_features
)

number_features_df = pd.DataFrame(
    number_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, number_features_df],
    axis=1
)

print("✅ Number features added")

✅ Number features added

# **Text-length features**

In [111]:
def extract_text_length_features(text):
    text = str(text).strip()

    words = text.split()

    return {
        "char_count": len(text),
        "word_count": len(words)
    }

In [112]:
length_features = df["text_clean"].apply(
    extract_text_length_features
)

length_features_df = pd.DataFrame(
    length_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, length_features_df],
    axis=1
)

print("✅ Text-length features added")

✅ Text-length features added

# **Punctuation features**

In [113]:
def extract_punctuation_features(text):
    text = str(text)

    return {
        "exclamation_count": text.count("!"),
        "question_count": text.count("?"),
        "comma_count": text.count(","),
        "dot_count": text.count("."),
        "colon_count": text.count(":"),
        "special_char_count": len(
            re.findall(r"[^\w\s]", text, flags=re.UNICODE)
        )
    }

In [114]:
punctuation_features = df["text_clean"].apply(
    extract_punctuation_features
)

punctuation_features_df = pd.DataFrame(
    punctuation_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, punctuation_features_df],
    axis=1
)

print("✅ Punctuation features added")

✅ Punctuation features added

# **Currency features**

In [115]:
CURRENCY_PATTERN = re.compile(
    r"(?:৳|টাকা|BDT|Tk|USD|\$|€|£|¥)",
    re.IGNORECASE
)

def extract_currency_features(text):
    text = str(text)

    matches = CURRENCY_PATTERN.findall(text)

    return {
        "currency_count": len(matches),
        "has_currency": int(len(matches) > 0)
    }

In [116]:
currency_features = df["text_clean"].apply(
    extract_currency_features
)

currency_features_df = pd.DataFrame(
    currency_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, currency_features_df],
    axis=1
)

print("✅ Currency features added")

✅ Currency features added

# **Security keyword features**

In [117]:
SECURITY_KEYWORDS = [
    "otp",
    "verify",
    "verification",
    "login",
    "password",
    "passcode",
    "pin",
    "account",
    "অ্যাকাউন্ট",
    "যাচাই",
    "ভেরিফাই",
    "পাসওয়ার্ড",
    "পিন"
]

In [118]:
def extract_security_features(text):
    text = str(text).lower()

    found_keywords = []

    for keyword in SECURITY_KEYWORDS:
        if keyword.lower() in text:
            found_keywords.append(keyword)

    return {
        "security_keyword_count": len(found_keywords),
        "has_security_keyword": int(
            len(found_keywords) > 0
        )
    }

In [119]:
security_features = df["text_clean"].apply(
    extract_security_features
)

security_features_df = pd.DataFrame(
    security_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, security_features_df],
    axis=1
)

print("✅ Security keyword features added")

✅ Security keyword features added

# **Bangla/English ratio**

In [120]:
def extract_language_features(text):
    text = str(text)

    bangla_chars = re.findall(
        r"[\u0980-\u09FF]",
        text
    )

    english_chars = re.findall(
        r"[A-Za-z]",
        text
    )

    total_language_chars = (
        len(bangla_chars) +
        len(english_chars)
    )

    if total_language_chars == 0:
        bangla_ratio = 0.0
        english_ratio = 0.0
    else:
        bangla_ratio = (
            len(bangla_chars) /
            total_language_chars
        )

        english_ratio = (
            len(english_chars) /
            total_language_chars
        )

    return {
        "bangla_char_count": len(bangla_chars),
        "english_char_count": len(english_chars),
        "bangla_ratio": bangla_ratio,
        "english_ratio": english_ratio,
        "has_bangla": int(len(bangla_chars) > 0),
        "has_english": int(len(english_chars) > 0)
    }

In [121]:
language_features = df["text_clean"].apply(
    extract_language_features
)

language_features_df = pd.DataFrame(
    language_features.tolist(),
    index=df.index
)

df = pd.concat(
    [df, language_features_df],
    axis=1
)

print("✅ Language features added")

✅ Language features added

# **Check all newly created features**

In [122]:
new_feature_columns = [
    "phone_count",
    "has_phone",
    "digit_count",
    "number_count",
    "has_digits",
    "char_count",
    "word_count",
    "exclamation_count",
    "question_count",
    "comma_count",
    "dot_count",
    "colon_count",
    "special_char_count",
    "currency_count",
    "has_currency",
    "security_keyword_count",
    "has_security_keyword",
    "bangla_char_count",
    "english_char_count",
    "bangla_ratio",
    "english_ratio",
    "has_bangla",
    "has_english"
]

missing_features = [
    col for col in new_feature_columns
    if col not in df.columns
]

if missing_features:
    print("❌ Missing:", missing_features)
else:
    print("✅ All new text features are present")

✅ All new text features are present

# **ONE final list of structured features**

In [123]:
STRUCTURED_FEATURE_COLUMNS = [
    # URL
    "url_count",
    "url_total_length",
    "url_max_length",
    "url_digit_count",
    "url_dot_count",
    "url_hyphen_count",
    "url_slash_count",
    "url_has_https",
    "url_has_ip",
    "url_has_at",
    "url_is_shortened",

    # Phone
    "phone_count",
    "has_phone",

    # Numbers
    "digit_count",
    "number_count",
    "has_digits",

    # Text length
    "char_count",
    "word_count",

    # Punctuation
    "exclamation_count",
    "question_count",
    "comma_count",
    "dot_count",
    "colon_count",
    "special_char_count",

    # Currency
    "currency_count",
    "has_currency",

    # Security
    "security_keyword_count",
    "has_security_keyword",

    # Language
    "bangla_char_count",
    "english_char_count",
    "bangla_ratio",
    "english_ratio",
    "has_bangla",
    "has_english"
]

print("Total structured features:", len(STRUCTURED_FEATURE_COLUMNS))

Total structured features: 34

In [124]:
non_numeric_features = df[
    STRUCTURED_FEATURE_COLUMNS
].select_dtypes(
    exclude=["number"]
).columns.tolist()

if non_numeric_features:
    raise TypeError(
        f"These features are not numeric: "
        f"{non_numeric_features}"
    )

print("✅ All structured features are numeric")

✅ All structured features are numeric

In [125]:
missing_feature_values = (
    df[STRUCTURED_FEATURE_COLUMNS]
    .isnull()
    .sum()
)

print(
    missing_feature_values[
        missing_feature_values > 0
    ]
)

Series([], dtype: int64)

# **train/validation/test split**

In [126]:
from sklearn.model_selection import train_test_split

In [127]:
train_df, temp_df = train_test_split(
    df,
    test_size=0.20,
    random_state=SEED,
    stratify=df["label"]
)

print("Train:", train_df.shape)
print("Temporary:", temp_df.shape)

Train: (1002, 69)
Temporary: (251, 69)

In [128]:
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=SEED,
    stratify=temp_df["label"]
)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (1002, 69)
Validation: (125, 69)
Test: (126, 69)

# **___df___fjdfhdfhdfhdjahfdljkhfdjfhdajhfdkjhfahfdhfscalerscalerjkldkljfldskjfdslkfjdslkfjsdkfjsdlkfjsdkl;cjld;ksmclsdk;jf;klsdfj;dlsfjd;lksfjd;lskfjdslfscalerscaler__hjhfjahdfjhdajfhsdkfjsf_**

In [130]:
print("TRAIN")
print(train_df["label"].value_counts())
print()

print("VALIDATION")
print(val_df["label"].value_counts())
print()

print("TEST")
print(test_df["label"].value_counts())

TRAIN
label
smish     396
normal    361
promo     245
Name: count, dtype: int64

VALIDATION
label
smish     49
normal    45
promo     31
Name: count, dtype: int64

TEST
label
smish     50
normal    45
promo     31
Name: count, dtype: int64

In [131]:
print("df exists:", "df" in globals())

if "df" in globals():
    print("Dataset shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
else:
    print("❌ df does not exist. You need to load/run the previous preprocessing cells first.")

df exists: True
Dataset shape: (1253, 69)

Columns:
['label', 'text', 'source', 'has_url', 'label_id', 'text_original', 'text_normalized', 'urls', 'url_count', 'url_count.1', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_for_model', 'character_length', 'url_count.2', 'url_total_length.1', 'url_max_length.1', 'url_digit_count.1', 'url_dot_count.1', 'url_hyphen_count.1', 'url_slash_count.1', 'url_has_https.1', 'url_has_ip.1', 'url_has_at.1', 'url_is_shortened.1', 'url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'text_unicode', 'text_clean', 'phone_count', 'has_phone', 'digit_count', 'number_count', 'has_digits', 'char_count', 'word_count', 'exclamation_count', 'question_count', 'comma_count', 'dot_count', 'colon_count', 'special_char_count', 'currency_count', 'has_currency', 'security_keyword_count', 'has_security_keyword', 'bangla_char_count', 'english_char_count', 'bangla_ratio', 'english_ratio', 'has_bangla', 'has_english']

# **Check class percentages**

In [132]:
def show_distribution(name, data):
    print(f"\n{name}")

    percentages = (
        data["label"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print(percentages)

show_distribution("TRAIN", train_df)
show_distribution("VALIDATION", val_df)
show_distribution("TEST", test_df)

TRAIN
label
smish     39.52
normal    36.03
promo     24.45
Name: proportion, dtype: float64

VALIDATION
label
smish     39.2
normal    36.0
promo     24.8
Name: proportion, dtype: float64

TEST
label
smish     39.68
normal    35.71
promo     24.60
Name: proportion, dtype: float64

# **fit the scaler ONLY on training data**

In [133]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_structured = scaler.fit_transform(
    train_df[STRUCTURED_FEATURE_COLUMNS]
)

X_val_structured = scaler.transform(
    val_df[STRUCTURED_FEATURE_COLUMNS]
)

X_test_structured = scaler.transform(
    test_df[STRUCTURED_FEATURE_COLUMNS]
)

print("✅ Structured features scaled")
print("Train shape:", X_train_structured.shape)
print("Validation shape:", X_val_structured.shape)
print("Test shape:", X_test_structured.shape)

✅ Structured features scaled
Train shape: (1002, 45)
Validation shape: (125, 45)
Test shape: (126, 45)

In [134]:
print(STRUCTURED_FEATURE_COLUMNS)

['url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened', 'phone_count', 'has_phone', 'digit_count', 'number_count', 'has_digits', 'char_count', 'word_count', 'exclamation_count', 'question_count', 'comma_count', 'dot_count', 'colon_count', 'special_char_count', 'currency_count', 'has_currency', 'security_keyword_count', 'has_security_keyword', 'bangla_char_count', 'english_char_count', 'bangla_ratio', 'english_ratio', 'has_bangla', 'has_english']

In [135]:
missing_cols = [
    col for col in STRUCTURED_FEATURE_COLUMNS
    if col not in train_df.columns
]

print("Missing columns:", missing_cols)

Missing columns: []

In [136]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [137]:
X_train_structured = scaler.fit_transform(
    train_df[STRUCTURED_FEATURE_COLUMNS]
)

In [138]:
X_train_structured = scaler.fit_transform(
    train_df[STRUCTURED_FEATURE_COLUMNS]
)

In [139]:
X_val_structured = scaler.transform(
    val_df[STRUCTURED_FEATURE_COLUMNS]
)

In [140]:
X_test_structured = scaler.transform(
    test_df[STRUCTURED_FEATURE_COLUMNS]
)

In [141]:
print("✅ Scaling completed successfully")

print("Train structured shape:", X_train_structured.shape)
print("Validation structured shape:", X_val_structured.shape)
print("Test structured shape:", X_test_structured.shape)

✅ Scaling completed successfully
Train structured shape: (1002, 45)
Validation structured shape: (125, 45)
Test structured shape: (126, 45)

In [142]:
# TRAIN
X_train_structured = scaler.fit_transform(
    train_df[STRUCTURED_FEATURE_COLUMNS]
)

# VALIDATION
X_val_structured = scaler.transform(
    val_df[STRUCTURED_FEATURE_COLUMNS]
)

# TEST
X_test_structured = scaler.transform(
    test_df[STRUCTURED_FEATURE_COLUMNS]
)

# **Save the scaler**

In [143]:
import joblib

SCALER_PATH = os.path.join(
    MODEL_DIR,
    "structured_feature_scaler.pkl"
)

joblib.dump(
    scaler,
    SCALER_PATH
)

print("✅ Scaler saved:")
print(SCALER_PATH)

✅ Scaler saved:
/content/drive/MyDrive/Bangla_Smishing_Project/models/structured_feature_scaler.pkl

# **Analyze BanglaBERT token lengths**

In [144]:
def token_length(text):
    return len(
        tokenizer.encode(
            str(text),
            add_special_tokens=True,
            truncation=False
        )
    )

# **Calculate token lengths on the training data**

In [145]:
train_token_lengths = train_df[
    "text_for_model"
].apply(token_length)

print(
    train_token_lengths.describe()
)

count    1002.000000
mean       22.779441
std        14.348254
min         4.000000
25%        15.000000
50%        21.000000
75%        26.000000
max       138.000000
Name: text_for_model, dtype: float64

# **Inspect token-length percentiles**

In [146]:
percentiles = train_token_lengths.quantile(
    [0.50, 0.75, 0.90, 0.95, 0.99]
)

print(percentiles)

0.50    21.0
0.75    26.0
0.90    35.0
0.95    43.0
0.99    83.0
Name: text_for_model, dtype: float64

In [147]:
MAX_LENGTH = 128

# **Count how many messages would be truncated**

In [148]:
MAX_LENGTH = 128

truncated_count = (
    train_token_lengths > MAX_LENGTH
).sum()

truncated_percentage = (
    truncated_count /
    len(train_token_lengths)
) * 100

print("MAX_LENGTH:", MAX_LENGTH)
print("Messages above limit:", truncated_count)
print(
    "Percentage above limit:",
    round(truncated_percentage, 2),
    "%"
)

MAX_LENGTH: 128
Messages above limit: 2
Percentage above limit: 0.2 %

# **Create the BanglaBERT tokenizer function**

In [149]:
def tokenize_texts(texts):
    return tokenizer(
        texts.tolist(),
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH,
        return_tensors="pt"
    )

# **Test tokenization on 5 messages**

In [150]:
test_tokenized = tokenize_texts(
    train_df["text_for_model"].head(5)
)

print("Input IDs shape:")
print(test_tokenized["input_ids"].shape)

print("\nAttention mask shape:")
print(test_tokenized["attention_mask"].shape)

Input IDs shape:
torch.Size([5, 22])

Attention mask shape:
torch.Size([5, 22])

# **Calculate class weights**

In [151]:
from sklearn.utils.class_weight import compute_class_weight

classes = np.array([
    "normal",
    "promo",
    "smish"
])

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=train_df["label"]
)

class_weights_dict = {
    label: weight
    for label, weight in zip(
        classes,
        class_weights
    )
}

print("Class weights:")
print(class_weights_dict)

Class weights:
{np.str_('normal'): np.float64(0.925207756232687), np.str_('promo'): np.float64(1.363265306122449), np.str_('smish'): np.float64(0.8434343434343434)}

# **Convert weights into PyTorch tensor**

In [152]:
class_weights_tensor = torch.tensor(
    class_weights,
    dtype=torch.float
).to(device)

print(class_weights_tensor)

tensor([0.9252, 1.3633, 0.8434], device='cuda:0')

# **Final train/validation/test sanity check**

In [153]:
print("=" * 70)
print("FINAL SPLIT CHECK")
print("=" * 70)

print("Train rows      :", len(train_df))
print("Validation rows :", len(val_df))
print("Test rows       :", len(test_df))
print("Total            :", len(train_df) + len(val_df) + len(test_df))

print("\nTrain labels:")
print(train_df["label"].value_counts())

print("\nValidation labels:")
print(val_df["label"].value_counts())

print("\nTest labels:")
print(test_df["label"].value_counts())

======================================================================
FINAL SPLIT CHECK
======================================================================
Train rows      : 1002
Validation rows : 125
Test rows       : 126
Total            : 1253

Train labels:
label
smish     396
normal    361
promo     245
Name: count, dtype: int64

Validation labels:
label
smish     49
normal    45
promo     31
Name: count, dtype: int64

Test labels:
label
smish     50
normal    45
promo     31
Name: count, dtype: int64

# **Check for overlap between train/validation/test**

In [154]:
train_texts = set(train_df["text_original"])
val_texts = set(val_df["text_original"])
test_texts = set(test_df["text_original"])

train_val_overlap = train_texts.intersection(val_texts)
train_test_overlap = train_texts.intersection(test_texts)
val_test_overlap = val_texts.intersection(test_texts)

print("Train-Val overlap :", len(train_val_overlap))
print("Train-Test overlap:", len(train_test_overlap))
print("Val-Test overlap  :", len(val_test_overlap))

Train-Val overlap : 0
Train-Test overlap: 0
Val-Test overlap  : 0

# **Save the split datasets**

In [155]:
TRAIN_PATH = os.path.join(
    DATA_DIR,
    "train.csv"
)

VAL_PATH = os.path.join(
    DATA_DIR,
    "validation.csv"
)

TEST_PATH = os.path.join(
    DATA_DIR,
    "test.csv"
)

train_df.to_csv(
    TRAIN_PATH,
    index=False,
    encoding="utf-8-sig"
)

val_df.to_csv(
    VAL_PATH,
    index=False,
    encoding="utf-8-sig"
)

test_df.to_csv(
    TEST_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Train/validation/test datasets saved")

✅ Train/validation/test datasets saved

# **Save preprocessing configuration**

In [156]:
import json

preprocessing_config = {
    "text_column": "text_for_model",
    "original_text_column": "text_original",
    "normalized_text_column": "text_normalized",
    "label_column": "label",
    "label_id_column": "label_id",
    "labels": label2id,
    "model_name": MODEL_NAME,
    "max_length": MAX_LENGTH,
    "structured_features": STRUCTURED_FEATURE_COLUMNS,
    "url_features": URL_FEATURE_COLUMNS,
    "random_seed": SEED
}

CONFIG_PATH = os.path.join(
    RESULTS_DIR,
    "preprocessing_config.json"
)

with open(CONFIG_PATH, "w") as f:
    json.dump(
        preprocessing_config,
        f,
        indent=4,
        ensure_ascii=False
    )

print("✅ Preprocessing configuration saved")

✅ Preprocessing configuration saved

# **Final preprocessing validation**

In [157]:
print("=" * 75)
print("✅ PREPROCESSING FINAL CHECK")
print("=" * 75)

print("\nDATA")
print("Total rows:", len(df))
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

print("\nLABELS")
print(label2id)

print("\nTEXT")
print("Model text column:", "text_for_model")
print("MAX_LENGTH:", MAX_LENGTH)

print("\nSTRUCTURED FEATURES")
print("Number of features:", len(STRUCTURED_FEATURE_COLUMNS))

print("\nURL FEATURES")
print("Number of URL features:", len(URL_FEATURE_COLUMNS))

print("\nLEAKAGE CHECK")
print("Train-Val:", len(train_val_overlap))
print("Train-Test:", len(train_test_overlap))
print("Val-Test:", len(val_test_overlap))

print("\nSAVED FILES")
print(TRAIN_PATH)
print(VAL_PATH)
print(TEST_PATH)
print(SCALER_PATH)
print(CONFIG_PATH)

print("\n" + "=" * 75)
print("PREPROCESSING PHASE COMPLETE ✅")
print("=" * 75)

===========================================================================
✅ PREPROCESSING FINAL CHECK
===========================================================================

DATA
Total rows: 1253
Train: 1002
Validation: 125
Test: 126

LABELS
{'normal': 0, 'promo': 1, 'smish': 2}

TEXT
Model text column: text_for_model
MAX_LENGTH: 128

STRUCTURED FEATURES
Number of features: 34

URL FEATURES
Number of URL features: 11

LEAKAGE CHECK
Train-Val: 0
Train-Test: 0
Val-Test: 0

SAVED FILES
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/train.csv
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/validation.csv
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/test.csv
/content/drive/MyDrive/Bangla_Smishing_Project/models/structured_feature_scaler.pkl
/content/drive/MyDrive/Bangla_Smishing_Project/results/preprocessing_config.json

===========================================================================
PREPROCESSING PHASE COMPLETE ✅
===========================================================================

In [158]:
# ============================================================
# CELL 0 — Sanity check existing notebook state
# ============================================================

required_objects = [
    "df",
    "df_raw",
    "train_df",
    "val_df",
    "test_df",
    "tokenizer",
    "STRUCTURED_FEATURE_COLUMNS",
    "label2id",
    "id2label",
    "SEED",
]

missing_objects = [x for x in required_objects if x not in globals()]

if missing_objects:
    raise RuntimeError(
        f"These required variables are missing: {missing_objects}\n"
        "Do not continue until they exist."
    )

print("✅ Existing project objects found.")
print(f"Full dataframe: {df.shape}")
print(f"Train: {train_df.shape}")
print(f"Validation: {val_df.shape}")
print(f"Test: {test_df.shape}")
print(f"Structured features: {len(STRUCTURED_FEATURE_COLUMNS)}")

✅ Existing project objects found.
Full dataframe: (1253, 69)
Train: (1002, 69)
Validation: (125, 69)
Test: (126, 69)
Structured features: 34

In [159]:
# ============================================================
# CELL 1 — Structured feature scaling
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# ------------------------------------------------------------
# 1. Verify required columns exist
# ------------------------------------------------------------

missing_train_features = [
    col for col in STRUCTURED_FEATURE_COLUMNS
    if col not in train_df.columns
]

missing_val_features = [
    col for col in STRUCTURED_FEATURE_COLUMNS
    if col not in val_df.columns
]

missing_test_features = [
    col for col in STRUCTURED_FEATURE_COLUMNS
    if col not in test_df.columns
]

if missing_train_features:
    raise ValueError(
        f"Missing structured features in train_df: {missing_train_features}"
    )

if missing_val_features:
    raise ValueError(
        f"Missing structured features in val_df: {missing_val_features}"
    )

if missing_test_features:
    raise ValueError(
        f"Missing structured features in test_df: {missing_test_features}"
    )

# ------------------------------------------------------------
# 2. Check missing values
# ------------------------------------------------------------

for name, split_df in [
    ("train", train_df),
    ("validation", val_df),
    ("test", test_df)
]:
    missing_count = split_df[STRUCTURED_FEATURE_COLUMNS].isna().sum().sum()

    print(f"{name}: missing structured values = {missing_count}")

    if missing_count > 0:
        raise ValueError(
            f"{name} contains missing structured feature values."
        )

# ------------------------------------------------------------
# 3. Convert to numeric
# ------------------------------------------------------------

X_train_raw = train_df[STRUCTURED_FEATURE_COLUMNS].apply(
    pd.to_numeric,
    errors="raise"
)

X_val_raw = val_df[STRUCTURED_FEATURE_COLUMNS].apply(
    pd.to_numeric,
    errors="raise"
)

X_test_raw = test_df[STRUCTURED_FEATURE_COLUMNS].apply(
    pd.to_numeric,
    errors="raise"
)

# ------------------------------------------------------------
# 4. Fit scaler ONLY on training data
# ------------------------------------------------------------

scaler = StandardScaler()

X_train_structured = scaler.fit_transform(X_train_raw)

# Validation/test ONLY transform
X_val_structured = scaler.transform(X_val_raw)
X_test_structured = scaler.transform(X_test_raw)

print("✅ Structured features scaled successfully.")

print("Train shape:", X_train_structured.shape)
print("Validation shape:", X_val_structured.shape)
print("Test shape:", X_test_structured.shape)

train: missing structured values = 0
validation: missing structured values = 0
test: missing structured values = 0
✅ Structured features scaled successfully.
Train shape: (1002, 45)
Validation shape: (125, 45)
Test shape: (126, 45)

In [160]:
# ============================================================
# CELL 2 — Verify scaling
# ============================================================

print("Train mean:")
print(np.mean(X_train_structured, axis=0)[:10])

print("\nTrain std:")
print(np.std(X_train_structured, axis=0)[:10])

# Train should have approximately mean 0 and std 1
train_means = np.mean(X_train_structured, axis=0)
train_stds = np.std(X_train_structured, axis=0)

if not np.allclose(train_means, 0, atol=1e-6):
    print("⚠️ Some training feature means are not exactly 0.")

if not np.allclose(train_stds, 1, atol=1e-6):
    print("⚠️ Some training feature std values are not exactly 1.")

print("\n✅ Scaling verification completed.")

Train mean:
[ 1.02823051e-16  1.02823051e-16  1.50688953e-17  1.50688953e-17
  5.31843365e-17  5.31843365e-17  3.72290356e-17  3.72290356e-17
 -5.76163646e-17 -5.76163646e-17]

Train std:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
⚠️ Some training feature std values are not exactly 1.

✅ Scaling verification completed.

In [161]:
# ============================================================
# DIAGNOSTIC — Find the 35th feature
# ============================================================

print("Number of STRUCTURED_FEATURE_COLUMNS:",
      len(STRUCTURED_FEATURE_COLUMNS))

print("\nSTRUCTURED_FEATURE_COLUMNS:")
for i, col in enumerate(STRUCTURED_FEATURE_COLUMNS):
    print(i, col)

print("\nX_train_structured shape:",
      X_train_structured.shape)

print("\nX_train_raw shape:",
      X_train_raw.shape)

Number of STRUCTURED_FEATURE_COLUMNS: 34

STRUCTURED_FEATURE_COLUMNS:
0 url_count
1 url_total_length
2 url_max_length
3 url_digit_count
4 url_dot_count
5 url_hyphen_count
6 url_slash_count
7 url_has_https
8 url_has_ip
9 url_has_at
10 url_is_shortened
11 phone_count
12 has_phone
13 digit_count
14 number_count
15 has_digits
16 char_count
17 word_count
18 exclamation_count
19 question_count
20 comma_count
21 dot_count
22 colon_count
23 special_char_count
24 currency_count
25 has_currency
26 security_keyword_count
27 has_security_keyword
28 bangla_char_count
29 english_char_count
30 bangla_ratio
31 english_ratio
32 has_bangla
33 has_english

X_train_structured shape: (1002, 45)

X_train_raw shape: (1002, 45)

In [162]:
# ============================================================
# DIAGNOSTIC — Compare actual dataframe columns with feature list
# ============================================================

actual_numeric_columns = list(
    X_train_raw.columns
)

print("Actual numeric feature count:",
      len(actual_numeric_columns))

print("Feature-list count:",
      len(STRUCTURED_FEATURE_COLUMNS))

print("\nActual columns:")
for i, col in enumerate(actual_numeric_columns):
    print(i, col)

print("\nFeature-list columns:")
for i, col in enumerate(STRUCTURED_FEATURE_COLUMNS):
    print(i, col)

Actual numeric feature count: 45
Feature-list count: 34

Actual columns:
0 url_count
1 url_count
2 url_total_length
3 url_total_length
4 url_max_length
5 url_max_length
6 url_digit_count
7 url_digit_count
8 url_dot_count
9 url_dot_count
10 url_hyphen_count
11 url_hyphen_count
12 url_slash_count
13 url_slash_count
14 url_has_https
15 url_has_https
16 url_has_ip
17 url_has_ip
18 url_has_at
19 url_has_at
20 url_is_shortened
21 url_is_shortened
22 phone_count
23 has_phone
24 digit_count
25 number_count
26 has_digits
27 char_count
28 word_count
29 exclamation_count
30 question_count
31 comma_count
32 dot_count
33 colon_count
34 special_char_count
35 currency_count
36 has_currency
37 security_keyword_count
38 has_security_keyword
39 bangla_char_count
40 english_char_count
41 bangla_ratio
42 english_ratio
43 has_bangla
44 has_english

Feature-list columns:
0 url_count
1 url_total_length
2 url_max_length
3 url_digit_count
4 url_dot_count
5 url_hyphen_count
6 url_slash_count
7 url_has_https
8 url_has_ip
9 url_has_at
10 url_is_shortened
11 phone_count
12 has_phone
13 digit_count
14 number_count
15 has_digits
16 char_count
17 word_count
18 exclamation_count
19 question_count
20 comma_count
21 dot_count
22 colon_count
23 special_char_count
24 currency_count
25 has_currency
26 security_keyword_count
27 has_security_keyword
28 bangla_char_count
29 english_char_count
30 bangla_ratio
31 english_ratio
32 has_bangla
33 has_english

In [163]:
# ============================================================
# DIAGNOSTIC — Find extra/missing feature names
# ============================================================

actual_set = set(X_train_raw.columns)
planned_set = set(STRUCTURED_FEATURE_COLUMNS)

extra_features = actual_set - planned_set
missing_features = planned_set - actual_set

print("Features present in X_train_raw but NOT in STRUCTURED_FEATURE_COLUMNS:")
print(extra_features)

print("\nFeatures present in STRUCTURED_FEATURE_COLUMNS but NOT in X_train_raw:")
print(missing_features)

Features present in X_train_raw but NOT in STRUCTURED_FEATURE_COLUMNS:
set()

Features present in STRUCTURED_FEATURE_COLUMNS but NOT in X_train_raw:
set()

In [164]:
# ============================================================
# STEP 1 — Check for duplicate feature names
# ============================================================

duplicate_features = [
    col
    for col in STRUCTURED_FEATURE_COLUMNS
    if STRUCTURED_FEATURE_COLUMNS.count(col) > 1
]

print("Number of features:",
      len(STRUCTURED_FEATURE_COLUMNS))

print("Number of unique features:",
      len(set(STRUCTURED_FEATURE_COLUMNS)))

print("Duplicate features:")
print(set(duplicate_features))

assert len(STRUCTURED_FEATURE_COLUMNS) == len(
    set(STRUCTURED_FEATURE_COLUMNS)
)

print("✅ STRUCTURED_FEATURE_COLUMNS contains no duplicates.")

Number of features: 34
Number of unique features: 34
Duplicate features:
set()
✅ STRUCTURED_FEATURE_COLUMNS contains no duplicates.

In [165]:
# ============================================================
# STEP 1 — Find duplicate dataframe columns
# ============================================================

print("Train duplicate columns:")
print(train_df.columns[train_df.columns.duplicated()].tolist())

print("\nValidation duplicate columns:")
print(val_df.columns[val_df.columns.duplicated()].tolist())

print("\nTest duplicate columns:")
print(test_df.columns[test_df.columns.duplicated()].tolist())

Train duplicate columns:
['url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened']

Validation duplicate columns:
['url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened']

Test duplicate columns:
['url_count', 'url_total_length', 'url_max_length', 'url_digit_count', 'url_dot_count', 'url_hyphen_count', 'url_slash_count', 'url_has_https', 'url_has_ip', 'url_has_at', 'url_is_shortened']

In [166]:
# ============================================================
# STEP 2 — Remove duplicate columns
# ============================================================

train_df = train_df.loc[
    :,
    ~train_df.columns.duplicated()
].copy()

val_df = val_df.loc[
    :,
    ~val_df.columns.duplicated()
].copy()

test_df = test_df.loc[
    :,
    ~test_df.columns.duplicated()
].copy()

print("Train shape after removing duplicate columns:",
      train_df.shape)

print("Validation shape after removing duplicate columns:",
      val_df.shape)

print("Test shape after removing duplicate columns:",
      test_df.shape)

Train shape after removing duplicate columns: (1002, 58)
Validation shape after removing duplicate columns: (125, 58)
Test shape after removing duplicate columns: (126, 58)

In [167]:
# ============================================================
# STEP 3 — Verify url_count is unique
# ============================================================

print(
    "Train url_count occurrences:",
    list(train_df.columns).count("url_count")
)

print(
    "Validation url_count occurrences:",
    list(val_df.columns).count("url_count")
)

print(
    "Test url_count occurrences:",
    list(test_df.columns).count("url_count")
)

assert list(train_df.columns).count("url_count") == 1
assert list(val_df.columns).count("url_count") == 1
assert list(test_df.columns).count("url_count") == 1

print("✅ url_count is unique in all splits.")

Train url_count occurrences: 1
Validation url_count occurrences: 1
Test url_count occurrences: 1
✅ url_count is unique in all splits.

In [168]:
# ============================================================
# STEP 4 — Recreate structured feature matrices
# ============================================================

X_train_raw = train_df[
    STRUCTURED_FEATURE_COLUMNS
].copy()

X_val_raw = val_df[
    STRUCTURED_FEATURE_COLUMNS
].copy()

X_test_raw = test_df[
    STRUCTURED_FEATURE_COLUMNS
].copy()

print("Train raw shape:", X_train_raw.shape)
print("Validation raw shape:", X_val_raw.shape)
print("Test raw shape:", X_test_raw.shape)

assert X_train_raw.shape[1] == 34
assert X_val_raw.shape[1] == 34
assert X_test_raw.shape[1] == 34

print("✅ All structured feature matrices contain exactly 34 features.")

Train raw shape: (1002, 34)
Validation raw shape: (125, 34)
Test raw shape: (126, 34)
✅ All structured feature matrices contain exactly 34 features.

In [169]:
# ============================================================
# STEP 5 — Scale the corrected 34 features
# ============================================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_structured = scaler.fit_transform(
    X_train_raw
)

X_val_structured = scaler.transform(
    X_val_raw
)

X_test_structured = scaler.transform(
    X_test_raw
)

print("Train scaled shape:",
      X_train_structured.shape)

print("Validation scaled shape:",
      X_val_structured.shape)

print("Test scaled shape:",
      X_test_structured.shape)

assert X_train_structured.shape == (1002, 34)
assert X_val_structured.shape == (125, 34)
assert X_test_structured.shape == (126, 34)

print("\n✅ Scaling successfully completed.")

Train scaled shape: (1002, 34)
Validation scaled shape: (125, 34)
Test scaled shape: (126, 34)

✅ Scaling successfully completed.

In [170]:
# ============================================================
# STEP 6 — Verify scaling
# ============================================================

train_means = np.mean(
    X_train_structured,
    axis=0
)

train_stds = np.std(
    X_train_structured,
    axis=0
)

print("Maximum absolute training mean:",
      np.max(np.abs(train_means)))

print("Minimum training standard deviation:",
      np.min(train_stds))

print("\nZero-variance ORIGINAL features:")

original_stds = X_train_raw.std()

zero_variance_features = original_stds[
    original_stds == 0
].index.tolist()

print(zero_variance_features)

print("\n✅ Scaling verification completed.")

Maximum absolute training mean: 1.0282305058404644e-16
Minimum training standard deviation: 0.0

Zero-variance ORIGINAL features:
['url_has_ip', 'url_has_at']

✅ Scaling verification completed.

In [171]:
# ============================================================
# STEP 7 — Create scaled feature names
# ============================================================

SCALED_FEATURE_COLUMNS = [
    f"scaled_{col}"
    for col in STRUCTURED_FEATURE_COLUMNS
]

print(
    "Number of scaled feature names:",
    len(SCALED_FEATURE_COLUMNS)
)

print(
    "Number of scaled data columns:",
    X_train_structured.shape[1]
)

assert len(SCALED_FEATURE_COLUMNS) == 34
assert X_train_structured.shape[1] == 34

print("✅ Feature names and scaled data match.")

Number of scaled feature names: 34
Number of scaled data columns: 34
✅ Feature names and scaled data match.

In [172]:
# ============================================================
# STEP 8 — Attach scaled features
# ============================================================

# Remove scaled columns if this cell was previously run
train_df = train_df.drop(
    columns=SCALED_FEATURE_COLUMNS,
    errors="ignore"
)

val_df = val_df.drop(
    columns=SCALED_FEATURE_COLUMNS,
    errors="ignore"
)

test_df = test_df.drop(
    columns=SCALED_FEATURE_COLUMNS,
    errors="ignore"
)

# Create DataFrames
train_scaled_df = pd.DataFrame(
    X_train_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=train_df.index
)

val_scaled_df = pd.DataFrame(
    X_val_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=val_df.index
)

test_scaled_df = pd.DataFrame(
    X_test_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=test_df.index
)

# Attach
train_df = pd.concat(
    [train_df, train_scaled_df],
    axis=1
)

val_df = pd.concat(
    [val_df, val_scaled_df],
    axis=1
)

test_df = pd.concat(
    [test_df, test_scaled_df],
    axis=1
)

print("✅ Scaled features attached successfully.")

print(
    "\nNumber of scaled features:",
    len(SCALED_FEATURE_COLUMNS)
)

print(
    "Train scaled matrix:",
    X_train_structured.shape
)

✅ Scaled features attached successfully.

Number of scaled features: 34
Train scaled matrix: (1002, 34)

In [173]:
# ============================================================
# CELL 3 — Store scaled structured features
# ============================================================

SCALED_FEATURE_COLUMNS = [
    f"scaled_{col}"
    for col in STRUCTURED_FEATURE_COLUMNS
]

train_df = train_df.copy()
val_df = val_df.copy()
test_df = test_df.copy()

train_scaled_df = pd.DataFrame(
    X_train_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=train_df.index
)

val_scaled_df = pd.DataFrame(
    X_val_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=val_df.index
)

test_scaled_df = pd.DataFrame(
    X_test_structured,
    columns=SCALED_FEATURE_COLUMNS,
    index=test_df.index
)

train_df = pd.concat([train_df, train_scaled_df], axis=1)
val_df = pd.concat([val_df, val_scaled_df], axis=1)
test_df = pd.concat([test_df, test_scaled_df], axis=1)

print("✅ Scaled features attached.")

print(
    train_df[
        SCALED_FEATURE_COLUMNS[:5]
    ].head()
)

✅ Scaled features attached.
      scaled_url_count  scaled_url_count  scaled_url_total_length  \
323          -0.681189         -0.681189                -0.572185
166           1.326315          1.326315                 1.434802
140          -0.681189         -0.681189                -0.572185
1018          1.326315          1.326315                 0.765806
1230          1.326315          1.326315                 2.178130

      scaled_url_total_length  scaled_url_max_length  scaled_url_max_length  \
323                 -0.572185              -0.572911              -0.572911
166                  1.434802               1.459548               1.459548
140                 -0.572185              -0.572911              -0.572911
1018                 0.765806               0.782062               0.782062
1230                 2.178130               2.212311               2.212311

      scaled_url_digit_count  scaled_url_digit_count  scaled_url_dot_count  \
323                -0.261883               -0.261883             -0.606309
166                -0.261883               -0.261883              0.901188
140                -0.261883               -0.261883             -0.606309
1018               -0.261883               -0.261883              0.901188
1230               -0.261883               -0.261883              2.408685

      scaled_url_dot_count
323              -0.606309
166               0.901188
140              -0.606309
1018              0.901188
1230              2.408685

In [174]:
# ============================================================
# CELL 4 — Verify class distributions
# ============================================================

def show_distribution(name, split_df):
    print(f"\n===== {name.upper()} =====")

    counts = split_df["label"].value_counts().reindex(
        ["normal", "promo", "smish"],
        fill_value=0
    )

    percentages = (
        split_df["label"]
        .value_counts(normalize=True)
        .reindex(
            ["normal", "promo", "smish"],
            fill_value=0
        ) * 100
    )

    result = pd.DataFrame({
        "count": counts,
        "percentage": percentages.round(2)
    })

    print(result)

show_distribution("train", train_df)
show_distribution("validation", val_df)
show_distribution("test", test_df)

===== TRAIN =====
        count  percentage
label
normal    361       36.03
promo     245       24.45
smish     396       39.52

===== VALIDATION =====
        count  percentage
label
normal     45        36.0
promo      31        24.8
smish      49        39.2

===== TEST =====
        count  percentage
label
normal     45       35.71
promo      31       24.60
smish      50       39.68

In [175]:
# ============================================================
# CELL 5 — Final SMS leakage check
# ============================================================

train_texts = set(train_df["text_original"].astype(str))
val_texts = set(val_df["text_original"].astype(str))
test_texts = set(test_df["text_original"].astype(str))

train_val_overlap = train_texts.intersection(val_texts)
train_test_overlap = train_texts.intersection(test_texts)
val_test_overlap = val_texts.intersection(test_texts)

print("Train ↔ Validation overlap:", len(train_val_overlap))
print("Train ↔ Test overlap:", len(train_test_overlap))
print("Validation ↔ Test overlap:", len(val_test_overlap))

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

print("✅ No exact SMS overlap between splits.")

Train ↔ Validation overlap: 0
Train ↔ Test overlap: 0
Validation ↔ Test overlap: 0
✅ No exact SMS overlap between splits.

In [176]:
# ============================================================
# CELL 5 — Final SMS leakage check
# ============================================================

train_texts = set(train_df["text_original"].astype(str))
val_texts = set(val_df["text_original"].astype(str))
test_texts = set(test_df["text_original"].astype(str))

train_val_overlap = train_texts.intersection(val_texts)
train_test_overlap = train_texts.intersection(test_texts)
val_test_overlap = val_texts.intersection(test_texts)

print("Train ↔ Validation overlap:", len(train_val_overlap))
print("Train ↔ Test overlap:", len(train_test_overlap))
print("Validation ↔ Test overlap:", len(val_test_overlap))

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

print("✅ No exact SMS overlap between splits.")

Train ↔ Validation overlap: 0
Train ↔ Test overlap: 0
Validation ↔ Test overlap: 0
✅ No exact SMS overlap between splits.

In [177]:
# ============================================================
# CELL 6 — Verify label encoding
# ============================================================

print("label2id:", label2id)
print("id2label:", id2label)

expected_label2id = {
    "normal": 0,
    "promo": 1,
    "smish": 2
}

assert label2id == expected_label2id

for name, split_df in [
    ("train", train_df),
    ("validation", val_df),
    ("test", test_df)
]:
    assert split_df["label_id"].notna().all()
    assert set(split_df["label_id"].unique()).issubset({0, 1, 2})

    print(
        f"{name}: "
        f"{sorted(split_df['label_id'].unique().tolist())}"
    )

print("✅ Label encoding verified.")

label2id: {'normal': 0, 'promo': 1, 'smish': 2}
id2label: {0: 'normal', 1: 'promo', 2: 'smish'}
train: [0, 1, 2]
validation: [0, 1, 2]
test: [0, 1, 2]
✅ Label encoding verified.

In [178]:
# ============================================================
# CELL 7 — Calculate class weights
# ============================================================

from sklearn.utils.class_weight import compute_class_weight

classes = np.array([0, 1, 2])

class_weights_array = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=train_df["label_id"].values
)

class_weights_dict = {
    int(cls): float(weight)
    for cls, weight in zip(classes, class_weights_array)
}

print("Class weights:")
for class_id, weight in class_weights_dict.items():
    print(
        f"{id2label[class_id]} ({class_id}) → {weight:.4f}"
    )

Class weights:
normal (0) → 0.9252
promo (1) → 1.3633
smish (2) → 0.8434

In [179]:
import torch

class_weights_tensor = torch.tensor(
    class_weights_array,
    dtype=torch.float32
)

In [180]:
# ============================================================
# CELL 8 — Token-length analysis
# ============================================================

from tqdm.auto import tqdm

def get_token_lengths(texts, tokenizer, batch_size=64):
    lengths = []

    texts = list(texts)

    for start in tqdm(
        range(0, len(texts), batch_size),
        desc="Analyzing token lengths"
    ):
        batch = texts[start:start + batch_size]

        encoded = tokenizer(
            batch,
            add_special_tokens=True,
            padding=False,
            truncation=False,
            return_length=True
        )

        lengths.extend(encoded["length"])

    return np.array(lengths)


all_lengths = get_token_lengths(
    df["text_for_model"].astype(str).tolist(),
    tokenizer
)

print("Number of SMS:", len(all_lengths))

print("\nToken length statistics:")
print(
    pd.Series(all_lengths).describe(
        percentiles=[
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

Analyzing token lengths:   0%|          | 0/20 [00:00<?, ?it/s]

Number of SMS: 1253

Token length statistics:
count    1253.000000
mean       22.801277
std        14.092787
min         4.000000
50%        21.000000
75%        27.000000
90%        35.000000
95%        44.000000
99%        81.960000
max       138.000000
dtype: float64

In [181]:
# ============================================================
# CELL 9 — Compare candidate MAX_LENGTH values
# ============================================================

candidate_lengths = [64, 96, 128, 160, 192, 256]

print(
    f"{'MAX_LENGTH':<15}"
    f"{'Truncated SMS':<20}"
    f"{'Truncation %':<15}"
)

for max_len in candidate_lengths:

    # Number whose natural length is greater than max_len
    truncated_count = np.sum(all_lengths > max_len)

    truncation_percentage = (
        truncated_count / len(all_lengths)
    ) * 100

    print(
        f"{max_len:<15}"
        f"{truncated_count:<20}"
        f"{truncation_percentage:.2f}%"
    )

MAX_LENGTH     Truncated SMS       Truncation %
64             24                  1.92%
96             5                   0.40%
128            2                   0.16%
160            0                   0.00%
192            0                   0.00%
256            0                   0.00%

In [182]:
# ============================================================
# CELL 10 — Final tokenizer configuration
# ============================================================

MAX_LENGTH = 128
TOKENIZER_PADDING = "max_length"
TOKENIZER_TRUNCATION = True

print("MAX_LENGTH =", MAX_LENGTH)
print("Padding =", TOKENIZER_PADDING)
print("Truncation =", TOKENIZER_TRUNCATION)

MAX_LENGTH = 128
Padding = max_length
Truncation = True

In [183]:
# ============================================================
# CELL 11 — Test tokenization on one SMS
# ============================================================

sample_text = train_df["text_for_model"].iloc[0]

sample_encoding = tokenizer(
    sample_text,
    padding="max_length",
    truncation=True,
    max_length=MAX_LENGTH,
    return_tensors="pt"
)

print("Text:")
print(sample_text)

print("\ninput_ids shape:")
print(sample_encoding["input_ids"].shape)

print("\nattention_mask shape:")
print(sample_encoding["attention_mask"].shape)

print("\nFirst 20 token IDs:")
print(sample_encoding["input_ids"][0][:20])

assert sample_encoding["input_ids"].shape == (1, MAX_LENGTH)
assert sample_encoding["attention_mask"].shape == (1, MAX_LENGTH)

print("\n✅ Single-text tokenization works.")

Text:
কেমন আছেন?

input_ids shape:
torch.Size([1, 128])

attention_mask shape:
torch.Size([1, 128])

First 20 token IDs:
tensor([   2, 1754, 2274,   35,    3,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])

✅ Single-text tokenization works.

In [184]:
# ============================================================
# CELL 12 — Tokenize all splits
# ============================================================

def tokenize_split(split_df, tokenizer, max_length):

    texts = split_df["text_for_model"].astype(str).tolist()

    encodings = tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=max_length,
        return_attention_mask=True
    )

    return encodings


train_encodings = tokenize_split(
    train_df,
    tokenizer,
    MAX_LENGTH
)

val_encodings = tokenize_split(
    val_df,
    tokenizer,
    MAX_LENGTH
)

test_encodings = tokenize_split(
    test_df,
    tokenizer,
    MAX_LENGTH
)

print("✅ Tokenization completed.")

print(
    "Train input_ids:",
    len(train_encodings["input_ids"])
)

print(
    "Validation input_ids:",
    len(val_encodings["input_ids"])
)

print(
    "Test input_ids:",
    len(test_encodings["input_ids"])
)

✅ Tokenization completed.
Train input_ids: 1002
Validation input_ids: 125
Test input_ids: 126

In [185]:
# ============================================================
# CELL 13 — Verify tokenized arrays
# ============================================================

for name, encodings, expected_rows in [
    ("train", train_encodings, len(train_df)),
    ("validation", val_encodings, len(val_df)),
    ("test", test_encodings, len(test_df))
]:

    input_ids = np.array(encodings["input_ids"])
    attention_mask = np.array(encodings["attention_mask"])

    print(f"\n{name.upper()}")

    print("input_ids:", input_ids.shape)
    print("attention_mask:", attention_mask.shape)

    assert input_ids.shape == (
        expected_rows,
        MAX_LENGTH
    )

    assert attention_mask.shape == (
        expected_rows,
        MAX_LENGTH
    )

print("\n✅ All tokenized shapes are correct.")

TRAIN
input_ids: (1002, 128)
attention_mask: (1002, 128)

VALIDATION
input_ids: (125, 128)
attention_mask: (125, 128)

TEST
input_ids: (126, 128)
attention_mask: (126, 128)

✅ All tokenized shapes are correct.

In [186]:
# ============================================================
# CELL 14 — Inspect padding
# ============================================================

sample_attention = np.array(
    train_encodings["attention_mask"][0]
)

print("Attention mask:")
print(sample_attention)

print(
    "\nNumber of real tokens:",
    sample_attention.sum()
)

print(
    "Number of padding positions:",
    len(sample_attention) - sample_attention.sum()
)

print("\n✅ Padding inspection complete.")

Attention mask:
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Number of real tokens: 5
Number of padding positions: 123

✅ Padding inspection complete.

In [187]:
# ============================================================
# CELL 15 — PyTorch Dataset
# ============================================================

import torch
from torch.utils.data import Dataset


class BanglaSmishingDataset(Dataset):

    def __init__(
        self,
        encodings,
        structured_features,
        labels
    ):

        self.input_ids = torch.tensor(
            encodings["input_ids"],
            dtype=torch.long
        )

        self.attention_mask = torch.tensor(
            encodings["attention_mask"],
            dtype=torch.long
        )

        self.structured_features = torch.tensor(
            structured_features,
            dtype=torch.float32
        )

        self.labels = torch.tensor(
            labels,
            dtype=torch.long
        )

        # ----------------------------------------------------
        # Safety checks
        # ----------------------------------------------------

        assert len(self.input_ids) == len(
            self.attention_mask
        )

        assert len(self.input_ids) == len(
            self.structured_features
        )

        assert len(self.input_ids) == len(
            self.labels
        )

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):

        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "structured_features": self.structured_features[idx],
            "labels": self.labels[idx]
        }

In [188]:
# ============================================================
# CELL 16 — Create datasets
# ============================================================

train_dataset = BanglaSmishingDataset(
    encodings=train_encodings,
    structured_features=X_train_structured,
    labels=train_df["label_id"].values
)

val_dataset = BanglaSmishingDataset(
    encodings=val_encodings,
    structured_features=X_val_structured,
    labels=val_df["label_id"].values
)

test_dataset = BanglaSmishingDataset(
    encodings=test_encodings,
    structured_features=X_test_structured,
    labels=test_df["label_id"].values
)

print("✅ PyTorch datasets created.")

print("Train:", len(train_dataset))
print("Validation:", len(val_dataset))
print("Test:", len(test_dataset))

✅ PyTorch datasets created.
Train: 1002
Validation: 125
Test: 126

In [189]:
# ============================================================
# CELL 17 — Test dataset item
# ============================================================

sample = train_dataset[0]

for key, value in sample.items():
    print(
        f"{key:<20}",
        "shape =", tuple(value.shape)
        if hasattr(value, "shape")
        else type(value),
        "dtype =", value.dtype
        if hasattr(value, "dtype")
        else None
    )

print("\n✅ Dataset item test completed.")

input_ids            shape = (128,) dtype = torch.int64
attention_mask       shape = (128,) dtype = torch.int64
structured_features  shape = (34,) dtype = torch.float32
labels               shape = () dtype = torch.int64

✅ Dataset item test completed.

In [190]:
# ============================================================
# CELL 18 — DataLoaders
# ============================================================

from torch.utils.data import DataLoader

BATCH_SIZE = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("✅ DataLoaders created.")

✅ DataLoaders created.

In [191]:
BATCH_SIZE = 32

In [192]:
# ============================================================
# CELL 19 — Test one DataLoader batch
# ============================================================

batch = next(iter(train_loader))

for key, value in batch.items():
    print(
        f"{key:<20}",
        tuple(value.shape),
        value.dtype
    )

print("\n✅ DataLoader batch works.")

input_ids            (16, 128) torch.int64
attention_mask       (16, 128) torch.int64
structured_features  (16, 34) torch.float32
labels               (16,) torch.int64

✅ DataLoader batch works.

In [193]:
# ============================================================
# CELL 20 — Save preprocessing artifacts
# ============================================================

import os
import joblib

PROJECT_ROOT = "/content/drive/MyDrive/Bangla_Smishing_Project"

MODEL_DIR = os.path.join(
    PROJECT_ROOT,
    "models"
)

RESULTS_DIR = os.path.join(
    PROJECT_ROOT,
    "results"
)

OUTPUT_DIR = os.path.join(
    PROJECT_ROOT,
    "outputs"
)

for directory in [
    MODEL_DIR,
    RESULTS_DIR,
    OUTPUT_DIR
]:
    os.makedirs(
        directory,
        exist_ok=True
    )

SCALER_PATH = os.path.join(
    MODEL_DIR,
    "structured_feature_scaler.pkl"
)

joblib.dump(
    scaler,
    SCALER_PATH
)

print("✅ Scaler saved:")
print(SCALER_PATH)

✅ Scaler saved:
/content/drive/MyDrive/Bangla_Smishing_Project/models/structured_feature_scaler.pkl

In [194]:
# ============================================================
# CELL 21 — Save tokenizer
# ============================================================

TOKENIZER_DIR = os.path.join(
    MODEL_DIR,
    "banglabert_tokenizer"
)

os.makedirs(
    TOKENIZER_DIR,
    exist_ok=True
)

tokenizer.save_pretrained(
    TOKENIZER_DIR
)

print("✅ Tokenizer saved:")
print(TOKENIZER_DIR)

✅ Tokenizer saved:
/content/drive/MyDrive/Bangla_Smishing_Project/models/banglabert_tokenizer

In [195]:
# ============================================================
# CELL 22 — Save final split CSVs
# ============================================================

DATASET_DIR = os.path.join(
    PROJECT_ROOT,
    "dataset"
)

os.makedirs(
    DATASET_DIR,
    exist_ok=True
)

train_path = os.path.join(
    DATASET_DIR,
    "train_processed.csv"
)

val_path = os.path.join(
    DATASET_DIR,
    "val_processed.csv"
)

test_path = os.path.join(
    DATASET_DIR,
    "test_processed.csv"
)

train_df.to_csv(
    train_path,
    index=False,
    encoding="utf-8-sig"
)

val_df.to_csv(
    val_path,
    index=False,
    encoding="utf-8-sig"
)

test_df.to_csv(
    test_path,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Processed splits saved.")
print(train_path)
print(val_path)
print(test_path)

✅ Processed splits saved.
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/train_processed.csv
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/val_processed.csv
/content/drive/MyDrive/Bangla_Smishing_Project/dataset/test_processed.csv

In [196]:
# ============================================================
# CELL 23 — Save preprocessing configuration
# ============================================================

import json

preprocessing_config = {
    "model_name": "csebuetnlp/banglabert",

    "label2id": label2id,
    "id2label": {
        str(k): v
        for k, v in id2label.items()
    },

    "structured_feature_columns": STRUCTURED_FEATURE_COLUMNS,

    "scaled_feature_columns": SCALED_FEATURE_COLUMNS,

    "max_length": MAX_LENGTH,

    "padding": TOKENIZER_PADDING,

    "truncation": TOKENIZER_TRUNCATION,

    "train_size": len(train_df),
    "validation_size": len(val_df),
    "test_size": len(test_df),

    "url_mask_token": "[URL]",

    "source_used_as_feature": False,

    "scaler_fit_on": "train_only"
}

CONFIG_PATH = os.path.join(
    RESULTS_DIR,
    "preprocessing_config.json"
)

with open(
    CONFIG_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        preprocessing_config,
        f,
        ensure_ascii=False,
        indent=4
    )

print("✅ Preprocessing configuration saved.")
print(CONFIG_PATH)

✅ Preprocessing configuration saved.
/content/drive/MyDrive/Bangla_Smishing_Project/results/preprocessing_config.json

In [197]:
# ============================================================
# CELL 24 — Save class weights
# ============================================================

CLASS_WEIGHT_PATH = os.path.join(
    RESULTS_DIR,
    "class_weights.json"
)

with open(
    CLASS_WEIGHT_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        {
            str(k): v
            for k, v in class_weights_dict.items()
        },
        f,
        indent=4
    )

print("✅ Class weights saved.")
print(CLASS_WEIGHT_PATH)

✅ Class weights saved.
/content/drive/MyDrive/Bangla_Smishing_Project/results/class_weights.json

In [198]:
# ============================================================
# CELL 25 — Save tokenized arrays
# ============================================================

TOKENIZED_DIR = os.path.join(
    OUTPUT_DIR,
    "tokenized"
)

os.makedirs(
    TOKENIZED_DIR,
    exist_ok=True
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "train_input_ids.npy"
    ),
    np.array(train_encodings["input_ids"])
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "train_attention_mask.npy"
    ),
    np.array(train_encodings["attention_mask"])
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "val_input_ids.npy"
    ),
    np.array(val_encodings["input_ids"])
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "val_attention_mask.npy"
    ),
    np.array(val_encodings["attention_mask"])
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "test_input_ids.npy"
    ),
    np.array(test_encodings["input_ids"])
)

np.save(
    os.path.join(
        TOKENIZED_DIR,
        "test_attention_mask.npy"
    ),
    np.array(test_encodings["attention_mask"])
)

print("✅ Tokenized arrays saved.")

✅ Tokenized arrays saved.

In [199]:
# ============================================================
# CELL 26 — FINAL PREPROCESSING CHECK
# ============================================================

print("=" * 60)
print("FINAL PREPROCESSING VERIFICATION")
print("=" * 60)

# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------

assert len(train_df) > 0
assert len(val_df) > 0
assert len(test_df) > 0

print("✅ Dataset splits exist")

# ------------------------------------------------------------
# Labels
# ------------------------------------------------------------

assert set(train_df["label_id"].unique()) <= {0, 1, 2}
assert set(val_df["label_id"].unique()) <= {0, 1, 2}
assert set(test_df["label_id"].unique()) <= {0, 1, 2}

print("✅ Labels valid")

# ------------------------------------------------------------
# Leakage
# ------------------------------------------------------------

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

print("✅ No SMS overlap")

# ------------------------------------------------------------
# Scaling
# ------------------------------------------------------------

assert X_train_structured.shape[0] == len(train_df)
assert X_val_structured.shape[0] == len(val_df)
assert X_test_structured.shape[0] == len(test_df)

assert X_train_structured.shape[1] == len(
    STRUCTURED_FEATURE_COLUMNS
)

print("✅ Structured features aligned")

# ------------------------------------------------------------
# Tokenization
# ------------------------------------------------------------

assert len(train_encodings["input_ids"]) == len(train_df)
assert len(val_encodings["input_ids"]) == len(val_df)
assert len(test_encodings["input_ids"]) == len(test_df)

print("✅ Tokenization aligned")

# ------------------------------------------------------------
# Dataset objects
# ------------------------------------------------------------

assert len(train_dataset) == len(train_df)
assert len(val_dataset) == len(val_df)
assert len(test_dataset) == len(test_df)

print("✅ PyTorch datasets aligned")

# ------------------------------------------------------------
# Required files
# ------------------------------------------------------------

required_files = [
    SCALER_PATH,
    CONFIG_PATH,
    CLASS_WEIGHT_PATH
]

for path in required_files:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing artifact: {path}"
        )

print("✅ Important artifacts exist")

print("\n" + "=" * 60)
print("🎉 PREPROCESSING PIPELINE COMPLETE")
print("=" * 60)

============================================================
FINAL PREPROCESSING VERIFICATION
============================================================
✅ Dataset splits exist
✅ Labels valid
✅ No SMS overlap
✅ Structured features aligned
✅ Tokenization aligned
✅ PyTorch datasets aligned
✅ Important artifacts exist

============================================================
🎉 PREPROCESSING PIPELINE COMPLETE
============================================================

In [200]:
# ============================================================
# CHECKPOINT — SAVE EVERYTHING WE WOULD NEED AFTER COLAB RESTART
# ============================================================

checkpoint = {
    "max_length": MAX_LENGTH,
    "structured_feature_columns": STRUCTURED_FEATURE_COLUMNS,
    "scaled_feature_columns": SCALED_FEATURE_COLUMNS,
    "label2id": label2id,
    "id2label": id2label,
    "class_weights": class_weights_dict,
    "train_rows": len(train_df),
    "val_rows": len(val_df),
    "test_rows": len(test_df)
}

checkpoint_path = os.path.join(
    RESULTS_DIR,
    "preprocessing_checkpoint.json"
)

with open(
    checkpoint_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        checkpoint,
        f,
        ensure_ascii=False,
        indent=4
    )

print("✅ Checkpoint saved:")
print(checkpoint_path)

✅ Checkpoint saved:
/content/drive/MyDrive/Bangla_Smishing_Project/results/preprocessing_checkpoint.json

In [201]:
import os

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"

print("Project exists:", os.path.exists(PROJECT_DIR))
print("\nFiles/folders:")

for item in os.listdir(PROJECT_DIR):
    print(" -", item)

Project exists: True

Files/folders:
 - dataset
 - models
 - outputs
 - results
 - notebooks

In [202]:
import os

for root, dirs, files in os.walk(PROJECT_DIR):
    for file in files:
        if file.endswith(".ipynb"):
            print(os.path.join(root, file))

/content/drive/MyDrive/Bangla_Smishing_Project/notebooks/Bangla_Smishing_Preprocessing.ipynb

In [203]:
import os

for root, dirs, files in os.walk(PROJECT_DIR):
    level = root.replace(PROJECT_DIR, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

Bangla_Smishing_Project/
    dataset/
        bangla_smishing_preprocessed.csv
        validation.csv
        test.csv
        train.csv
        val_processed.csv
        test_processed.csv
        train_processed.csv
    models/
        structured_feature_scaler.pkl
        banglabert_tokenizer/
            tokenizer_config.json
            tokenizer.json
    outputs/
        figures/
        confusion_matrices/
        predictions/
        tokenized/
            train_input_ids.npy
            train_attention_mask.npy
            test_attention_mask.npy
            test_input_ids.npy
            val_input_ids.npy
            val_attention_mask.npy
    results/
        environment_info.json
        class_weights.json
        preprocessing_config.json
        preprocessing_checkpoint.json
    notebooks/
        Bangla_Smishing_Preprocessing.ipynb

In [204]:
%cd /content
!rm -rf Multiclass-Bangla-Smishing-Detection
!git clone https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git

/content
Cloning into 'Multiclass-Bangla-Smishing-Detection'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 4), reused 20 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 447.52 KiB | 9.13 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [205]:
print(os.listdir(DATA_DIR))

['bangla_smishing_preprocessed.csv', 'validation.csv', 'test.csv', 'train.csv', 'val_processed.csv', 'test_processed.csv', 'train_processed.csv']

In [ ]:
%cd /content/Multiclass-Bangla-Smishing-Detection
!git status

/content/Multiclass-Bangla-Smishing-Detection
On branch main

No commits yet

nothing to commit (create/copy files and use "git add" to track)

In [ ]:
import os

REPO_DIR = "/content/Multiclass-Bangla-Smishing-Detection"

folders = [
    "notebooks",
    "data/raw",
    "data/processed",
    "preprocessing",
    "artifacts",
    "docs"
]

for folder in folders:
    os.makedirs(
        os.path.join(REPO_DIR, folder),
        exist_ok=True
    )

print("✅ Repository folders created.")

✅ Repository folders created.

In [ ]:
import shutil
import os

SOURCE_DATASET = os.path.join(
    PROJECT_DIR,
    "dataset",
    "hf_bangla_smishing.csv"
)

DEST_DATASET = os.path.join(
    REPO_DIR,
    "data",
    "raw",
    "hf_bangla_smishing.csv"
)

if os.path.exists(SOURCE_DATASET):
    shutil.copy2(
        SOURCE_DATASET,
        DEST_DATASET
    )
    print("✅ Raw dataset copied.")
else:
    print("⚠️ Dataset not found:", SOURCE_DATASET)

✅ Raw dataset copied.

In [ ]:
processed_files = {
    "train_processed.csv":
        os.path.join(REPO_DIR, "data", "processed"),

    "val_processed.csv":
        os.path.join(REPO_DIR, "data", "processed"),

    "test_processed.csv":
        os.path.join(REPO_DIR, "data", "processed")
}

for filename, destination_dir in processed_files.items():

    source = os.path.join(
        PROJECT_DIR,
        "dataset",
        filename
    )

    destination = os.path.join(
        destination_dir,
        filename
    )

    if os.path.exists(source):

        shutil.copy2(
            source,
            destination
        )

        print("✅ Copied:", filename)

    else:
        print("⚠️ Not found:", source)

✅ Copied: train_processed.csv
✅ Copied: val_processed.csv
✅ Copied: test_processed.csv

In [ ]:
SOURCE_SCALER = os.path.join(
    PROJECT_DIR,
    "models",
    "structured_feature_scaler.pkl"
)

DEST_SCALER = os.path.join(
    REPO_DIR,
    "artifacts",
    "structured_feature_scaler.pkl"
)

if os.path.exists(SOURCE_SCALER):

    shutil.copy2(
        SOURCE_SCALER,
        DEST_SCALER
    )

    print("✅ Scaler copied.")

else:
    print(
        "⚠️ Scaler not found:",
        SOURCE_SCALER
    )

✅ Scaler copied.

In [ ]:
files_to_copy = [
    "preprocessing_config.json",
    "class_weights.json"
]

for filename in files_to_copy:

    source = os.path.join(
        PROJECT_DIR,
        "results",
        filename
    )

    destination = os.path.join(
        REPO_DIR,
        "preprocessing",
        filename
    )

    if os.path.exists(source):

        shutil.copy2(
            source,
            destination
        )

        print("✅ Copied:", filename)

    else:
        print("⚠️ Not found:", source)

✅ Copied: preprocessing_config.json
✅ Copied: class_weights.json

In [ ]:
SOURCE_HANDOFF = "/mnt/data/Pasted markdown(3).md"

DEST_HANDOFF = os.path.join(
    REPO_DIR,
    "docs",
    "Bangla_Smishing_Project_Handoff.md"
)

if os.path.exists(SOURCE_HANDOFF):

    shutil.copy2(
        SOURCE_HANDOFF,
        DEST_HANDOFF
    )

    print("✅ Handoff document copied.")

else:
    print("⚠️ Handoff document not found.")

⚠️ Handoff document not found.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Bangla_Smishing_Project_Handoff_GitHub.md to Bangla_Smishing_Project_Handoff_GitHub.md

In [ ]:
from google.colab import files

uploaded = files.upload()

print("\nUploaded files:")
for filename in uploaded.keys():
    print("✅", filename)

Saving Bangla_Smishing_Project_Handoff_GitHub.md to Bangla_Smishing_Project_Handoff_GitHub (1).md

Uploaded files:
✅ Bangla_Smishing_Project_Handoff_GitHub (1).md

In [ ]:
import os
import shutil

SOURCE_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "results",
    "preprocessing_checkpoint.json"
)

DEST_CHECKPOINT = os.path.join(
    REPO_DIR,
    "preprocessing",
    "preprocessing_checkpoint.json"
)

if os.path.exists(SOURCE_CHECKPOINT):

    shutil.copy2(
        SOURCE_CHECKPOINT,
        DEST_CHECKPOINT
    )

    print("✅ Checkpoint copied.")

else:
    print(
        "⚠️ Checkpoint not found:",
        SOURCE_CHECKPOINT
    )

✅ Checkpoint copied.

In [ ]:
%cd /content/Multiclass-Bangla-Smishing-Detection

print("========== REPOSITORY CONTENTS ==========\n")

!find . -maxdepth 3 -type f | sort

/content/Multiclass-Bangla-Smishing-Detection
========== REPOSITORY CONTENTS ==========

./artifacts/structured_feature_scaler.pkl
./Bangla_Smishing_Project_Handoff_GitHub (1).md
./Bangla_Smishing_Project_Handoff_GitHub.md
./data/processed/test_processed.csv
./data/processed/train_processed.csv
./data/processed/val_processed.csv
./data/raw/hf_bangla_smishing.csv
./.git/config
./.git/description
./.git/HEAD
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-receive.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/update.sample
./.git/info/exclude
./preprocessing/class_weights.json
./preprocessing/preprocessing_checkpoint.json
./preprocessing/preprocessing_config.json

In [ ]:
import pandas as pd
import os

processed_dir = os.path.join(
    REPO_DIR,
    "data",
    "processed"
)

for filename in [
    "train_processed.csv",
    "val_processed.csv",
    "test_processed.csv"
]:

    path = os.path.join(
        processed_dir,
        filename
    )

    if os.path.exists(path):

        temp_df = pd.read_csv(path)

        duplicate_columns = temp_df.columns[
            temp_df.columns.duplicated()
        ].tolist()

        print(
            f"{filename}: "
            f"shape={temp_df.shape}, "
            f"duplicate_columns={duplicate_columns}"
        )

train_processed.csv: shape=(1002, 114), duplicate_columns=[]
val_processed.csv: shape=(125, 114), duplicate_columns=[]
test_processed.csv: shape=(126, 114), duplicate_columns=[]

In [ ]:
!du -sh .

3.6M	.

In [ ]:
!find . -type f -size +50M -print

In [ ]:
!find . -type f -size +50M -print

In [ ]:
!git status

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Bangla_Smishing_Project_Handoff_GitHub (1).md
	Bangla_Smishing_Project_Handoff_GitHub.md
	artifacts/
	data/
	preprocessing/

nothing added to commit but untracked files present (use "git add" to track)

In [ ]:
!git add .

In [ ]:
!git status

On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   Bangla_Smishing_Project_Handoff_GitHub (1).md
	new file:   Bangla_Smishing_Project_Handoff_GitHub.md
	new file:   artifacts/structured_feature_scaler.pkl
	new file:   data/processed/test_processed.csv
	new file:   data/processed/train_processed.csv
	new file:   data/processed/val_processed.csv
	new file:   data/raw/hf_bangla_smishing.csv
	new file:   preprocessing/class_weights.json
	new file:   preprocessing/preprocessing_checkpoint.json
	new file:   preprocessing/preprocessing_config.json

In [ ]:
!git commit -m "Add completed preprocessing pipeline and project handoff"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@233ef797003e.(none)')

In [ ]:
!git config --global user.name "sharifa5852"

In [ ]:
!git config --global user.email "sharifatunnur83@gmail.com"

In [ ]:
!git config --global user.name
!git config --global user.email

sharifa5852
sharifatunnur83@gmail.com

In [ ]:
!git commit -m "Add completed preprocessing pipeline and project handoff"

[main (root-commit) 8cecf3d] Add completed preprocessing pipeline and project handoff
 10 files changed, 5003 insertions(+)
 create mode 100644 Bangla_Smishing_Project_Handoff_GitHub (1).md
 create mode 100644 Bangla_Smishing_Project_Handoff_GitHub.md
 create mode 100644 artifacts/structured_feature_scaler.pkl
 create mode 100644 data/processed/test_processed.csv
 create mode 100644 data/processed/train_processed.csv
 create mode 100644 data/processed/val_processed.csv
 create mode 100644 data/raw/hf_bangla_smishing.csv
 create mode 100644 preprocessing/class_weights.json
 create mode 100644 preprocessing/preprocessing_checkpoint.json
 create mode 100644 preprocessing/preprocessing_config.json

In [ ]:
from getpass import getpass

github_token = getpass("Enter your GitHub token: ")

Enter your GitHub token: ··········

In [ ]:
import os

os.environ["GITHUB_TOKEN"] = github_token

In [ ]:
!git push https://sharifa5852:$GITHUB_TOKEN@github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git main

remote: Permission to Humaira201/Multiclass-Bangla-Smishing-Detection.git denied to Humaira201.
fatal: unable to access 'https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git/': The requested URL returned error: 403

In [ ]:
!git status

On branch main
Your branch is based on 'origin/main', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean

In [ ]:
!git log --oneline -3

8cecf3d (HEAD -> main) Add completed preprocessing pipeline and project handoff

In [ ]:
%cd /content/Multiclass-Bangla-Smishing-Detection

/content/Multiclass-Bangla-Smishing-Detection

In [ ]:
!git remote -v

origin	https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git (fetch)
origin	https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git (push)

In [ ]:
!git remote set-url origin https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git

In [ ]:
import os

os.environ.pop("GITHUB_TOKEN", None)

print("✅ Old token removed from environment.")

✅ Old token removed from environment.

In [ ]:
from getpass import getpass

GITHUB_TOKEN = getpass(
    "Paste your friend's GitHub Personal Access Token: "
)

Paste your friend's GitHub Personal Access Token: ··········

In [ ]:
import requests

response = requests.get(
    "https://api.github.com/user",
    headers={
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
)

print("Status:", response.status_code)

if response.status_code == 200:
    user_data = response.json()
    print("Authenticated GitHub username:", user_data["login"])
else:
    print("Authentication failed.")
    print(response.text[:500])

Status: 200
Authenticated GitHub username: Humaira201

In [ ]:
repo_response = requests.get(
    "https://api.github.com/repos/"
    "Humaira201/Multiclass-Bangla-Smishing-Detection",
    headers={
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
)

print("Status:", repo_response.status_code)

if repo_response.status_code == 200:
    repo_data = repo_response.json()

    print("Repository:", repo_data["full_name"])
    print("Private:", repo_data["private"])
    print("Permissions:")

    permissions = repo_data.get("permissions", {})

    print("  Admin:", permissions.get("admin"))
    print("  Push:", permissions.get("push"))
    print("  Pull:", permissions.get("pull"))

else:
    print(repo_response.text[:1000])

Status: 200
Repository: Humaira201/Multiclass-Bangla-Smishing-Detection
Private: False
Permissions:
  Admin: True
  Push: True
  Pull: True

In [ ]:
!git push https://Humaira201:$GITHUB_TOKEN@github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git main

Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 2 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 335.64 KiB | 2.41 MiB/s, done.
Total 16 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), done.
To https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection.git
 * [new branch]      main -> main

In [ ]:
!git status

On branch main
Your branch is based on 'origin/main', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean

In [ ]:
# ============================================================
# 1. GOOGLE DRIVE — SHOW EVERYTHING
# ============================================================

import os

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"

print("=" * 70)
print("GOOGLE DRIVE PROJECT")
print("=" * 70)

if not os.path.exists(PROJECT_DIR):
    print("❌ Project folder not found!")
else:
    for root, dirs, files in os.walk(PROJECT_DIR):
        level = root.replace(PROJECT_DIR, "").count(os.sep)
        indent = "    " * level

        print(f"{indent}{os.path.basename(root)}/")

        for file in sorted(files):
            path = os.path.join(root, file)
            size_kb = os.path.getsize(path) / 1024

            print(
                f"{indent}    {file} "
                f"({size_kb:.1f} KB)"
            )

======================================================================
GOOGLE DRIVE PROJECT
======================================================================
Bangla_Smishing_Project/
    notebooks/
        Bangla Smishing Detection - Main.ipynb (418.4 KB)
    dataset/
        bangla_smishing_preprocessed.csv (1058.9 KB)
        bangla_smishing_preprocessed.gsheet (0.2 KB)
        hf_bangla_smishing.csv (266.0 KB)
        test.csv (168.4 KB)
        test_processed.csv (327.5 KB)
        train.csv (1311.5 KB)
        train_processed.csv (2567.1 KB)
        val_processed.csv (318.4 KB)
        validation.csv (160.6 KB)
    models/
        structured_feature_scaler.pkl (2.2 KB)
        banglabert_tokenizer/
            tokenizer.json (1007.9 KB)
            tokenizer_config.json (0.4 KB)
    outputs/
        figures/
        confusion_matrices/
        predictions/
        tokenized/
            test_attention_mask.npy (126.1 KB)
            test_input_ids.npy (126.1 KB)
            train_attention_mask.npy (1002.1 KB)
            train_input_ids.npy (1002.1 KB)
            val_attention_mask.npy (125.1 KB)
            val_input_ids.npy (125.1 KB)
    results/
        class_weights.json (0.1 KB)
        environment_info.json (0.3 KB)
        preprocessing_checkpoint.json (2.4 KB)
        preprocessing_config.json (2.4 KB)

In [ ]:
# ============================================================
# 2. LOCAL GITHUB REPO IN COLAB
# ============================================================

REPO_DIR = "/content/Multiclass-Bangla-Smishing-Detection"

print("=" * 70)
print("LOCAL GITHUB REPOSITORY IN COLAB")
print("=" * 70)

if not os.path.exists(REPO_DIR):
    print("❌ Repository not found!")
else:
    for root, dirs, files in os.walk(REPO_DIR):
        # Don't show .git internals
        dirs[:] = [
            d for d in dirs
            if d != ".git"
        ]

        level = root.replace(REPO_DIR, "").count(os.sep)
        indent = "    " * level

        print(f"{indent}{os.path.basename(root)}/")

        for file in sorted(files):
            path = os.path.join(root, file)
            size_kb = os.path.getsize(path) / 1024

            print(
                f"{indent}    {file} "
                f"({size_kb:.1f} KB)"
            )

======================================================================
LOCAL GITHUB REPOSITORY IN COLAB
======================================================================
Multiclass-Bangla-Smishing-Detection/
    Bangla_Smishing_Project_Handoff_GitHub (1).md (15.2 KB)
    Bangla_Smishing_Project_Handoff_GitHub.md (15.2 KB)
    data/
        processed/
            test_processed.csv (327.5 KB)
            train_processed.csv (2567.1 KB)
            val_processed.csv (318.4 KB)
        raw/
            hf_bangla_smishing.csv (266.0 KB)
    docs/
    notebooks/
    preprocessing/
        class_weights.json (0.1 KB)
        preprocessing_checkpoint.json (2.4 KB)
        preprocessing_config.json (2.4 KB)
    artifacts/
        structured_feature_scaler.pkl (2.2 KB)

In [ ]:
# ============================================================
# 3. ACTUAL GITHUB MAIN BRANCH
# ============================================================

%cd /content/Multiclass-Bangla-Smishing-Detection

!git fetch origin main

print("=" * 70)
print("FILES ACTUALLY PRESENT ON GITHUB — origin/main")
print("=" * 70)

!git ls-tree -r --name-only origin/main

/content/Multiclass-Bangla-Smishing-Detection
From https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
======================================================================
FILES ACTUALLY PRESENT ON GITHUB — origin/main
======================================================================
Bangla_Smishing_Project_Handoff_GitHub (1).md
Bangla_Smishing_Project_Handoff_GitHub.md
artifacts/structured_feature_scaler.pkl
data/processed/test_processed.csv
data/processed/train_processed.csv
data/processed/val_processed.csv
data/raw/hf_bangla_smishing.csv
preprocessing/class_weights.json
preprocessing/preprocessing_checkpoint.json
preprocessing/preprocessing_config.json

In [ ]:
# ============================================================
# 4. LOCAL vs GITHUB SYNC
# ============================================================

%cd /content/Multiclass-Bangla-Smishing-Detection

!git fetch origin main

local_commit = !git rev-parse HEAD
remote_commit = !git rev-parse origin/main

print("Local commit :", local_commit[0])
print("GitHub commit:", remote_commit[0])

if local_commit[0] == remote_commit[0]:
    print("\n✅ Local repository and GitHub are synchronized.")
else:
    print("\n⚠️ Local repository and GitHub are NOT synchronized.")

/content/Multiclass-Bangla-Smishing-Detection
From https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection
 * branch            main       -> FETCH_HEAD
Local commit : 8cecf3d7baee1f326dbbf4812a6a7f5fd5fb7f1b
GitHub commit: 8cecf3d7baee1f326dbbf4812a6a7f5fd5fb7f1b

✅ Local repository and GitHub are synchronized.

In [ ]:
# ============================================================
# 5. LOCAL FILES vs GITHUB FILES
# ============================================================

import subprocess
import os

%cd /content/Multiclass-Bangla-Smishing-Detection

# Get local files
local_files = []

for root, dirs, files in os.walk(REPO_DIR):
    dirs[:] = [
        d for d in dirs
        if d != ".git"
    ]

    for file in files:
        full_path = os.path.join(root, file)
        relative_path = os.path.relpath(
            full_path,
            REPO_DIR
        )

        local_files.append(
            relative_path.replace("\\", "/")
        )

# Get GitHub files
github_output = subprocess.check_output(
    [
        "git",
        "ls-tree",
        "-r",
        "--name-only",
        "origin/main"
    ],
    text=True
)

github_files = [
    line.strip()
    for line in github_output.splitlines()
    if line.strip()
]

local_set = set(local_files)
github_set = set(github_files)

only_local = sorted(
    local_set - github_set
)

only_github = sorted(
    github_set - local_set
)

print("=" * 70)
print("LOCAL vs GITHUB")
print("=" * 70)

print("\nFiles in LOCAL but NOT in GitHub:")
if only_local:
    for file in only_local:
        print("❌", file)
else:
    print("✅ None")

print("\nFiles in GITHUB but NOT in LOCAL:")
if only_github:
    for file in only_github:
        print("⚠️", file)
else:
    print("✅ None")

/content/Multiclass-Bangla-Smishing-Detection
======================================================================
LOCAL vs GITHUB
======================================================================

Files in LOCAL but NOT in GitHub:
✅ None

Files in GITHUB but NOT in LOCAL:
✅ None

In [ ]:
# ============================================================
# 6. IMPORTANT PROJECT FILE CHECK
# ============================================================

important_files = [
    "README.md",
    "requirements.txt",
    ".gitignore",

    "notebooks/Bangla_Smishing_Preprocessing.ipynb",

    "data/raw/hf_bangla_smishing.csv",

    "data/processed/train_processed.csv",
    "data/processed/val_processed.csv",
    "data/processed/test_processed.csv",

    "preprocessing/class_weights.json",
    "preprocessing/preprocessing_config.json",
    "preprocessing/preprocessing_checkpoint.json",

    "artifacts/structured_feature_scaler.pkl",

    "docs/Bangla_Smishing_Project_Handoff.md"
]

print("=" * 70)
print("IMPORTANT FILES")
print("=" * 70)

for file in important_files:

    local_path = os.path.join(
        REPO_DIR,
        file
    )

    exists_local = os.path.exists(local_path)
    exists_github = file in github_set

    if exists_local and exists_github:
        status = "✅ LOCAL + GITHUB"

    elif exists_local and not exists_github:
        status = "⚠️ LOCAL ONLY"

    elif not exists_local and exists_github:
        status = "⚠️ GITHUB ONLY"

    else:
        status = "❌ MISSING"

    print(f"{status:<20} {file}")

======================================================================
IMPORTANT FILES
======================================================================
❌ MISSING            README.md
❌ MISSING            requirements.txt
❌ MISSING            .gitignore
❌ MISSING            notebooks/Bangla_Smishing_Preprocessing.ipynb
✅ LOCAL + GITHUB     data/raw/hf_bangla_smishing.csv
✅ LOCAL + GITHUB     data/processed/train_processed.csv
✅ LOCAL + GITHUB     data/processed/val_processed.csv
✅ LOCAL + GITHUB     data/processed/test_processed.csv
✅ LOCAL + GITHUB     preprocessing/class_weights.json
✅ LOCAL + GITHUB     preprocessing/preprocessing_config.json
✅ LOCAL + GITHUB     preprocessing/preprocessing_checkpoint.json
✅ LOCAL + GITHUB     artifacts/structured_feature_scaler.pkl
❌ MISSING            docs/Bangla_Smishing_Project_Handoff.md

In [ ]:
# ============================================================
# 7. CHECK PROCESSED DATASETS
# ============================================================

import pandas as pd

processed_files = [
    "train_processed.csv",
    "val_processed.csv",
    "test_processed.csv"
]

for filename in processed_files:

    path = os.path.join(
        REPO_DIR,
        "data",
        "processed",
        filename
    )

    print("\n" + "=" * 60)
    print(filename)

    if not os.path.exists(path):
        print("❌ FILE NOT FOUND")
        continue

    temp_df = pd.read_csv(path)

    print("Rows:", len(temp_df))
    print("Columns:", len(temp_df.columns))

    print(
        "Contains label_id:",
        "label_id" in temp_df.columns
    )

    print(
        "Contains text_for_model:",
        "text_for_model" in temp_df.columns
    )

    print(
        "Contains url_count:",
        "url_count" in temp_df.columns
    )

    duplicate_columns = temp_df.columns[
        temp_df.columns.duplicated()
    ].tolist()

    print(
        "Duplicate columns:",
        duplicate_columns
    )

============================================================
train_processed.csv
Rows: 1002
Columns: 114
Contains label_id: True
Contains text_for_model: True
Contains url_count: True
Duplicate columns: []

============================================================
val_processed.csv
Rows: 125
Columns: 114
Contains label_id: True
Contains text_for_model: True
Contains url_count: True
Duplicate columns: []

============================================================
test_processed.csv
Rows: 126
Columns: 114
Contains label_id: True
Contains text_for_model: True
Contains url_count: True
Duplicate columns: []

In [ ]:
# ============================================================
# 8. CHECK RAW DATASET
# ============================================================

raw_dataset = os.path.join(
    REPO_DIR,
    "data",
    "raw",
    "hf_bangla_smishing.csv"
)

raw_df = pd.read_csv(raw_dataset)

print("=" * 60)
print("RAW DATASET")
print("=" * 60)

print("Shape:", raw_df.shape)
print("Columns:", raw_df.columns.tolist())

print("\nLabel distribution:")
print(raw_df["label"].value_counts())

print("\nMissing values:")
print(raw_df.isna().sum())

============================================================
RAW DATASET
============================================================
Shape: (1253, 3)
Columns: ['label', 'text', 'source']

Label distribution:
label
smish     495
normal    451
promo     307
Name: count, dtype: int64

Missing values:
label     0
text      0
source    0
dtype: int64

In [ ]:
# ============================================================
# 9. DRIVE FILE vs GITHUB FILE HASH CHECK
# ============================================================

import hashlib

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        while True:
            chunk = f.read(1024 * 1024)

            if not chunk:
                break

            h.update(chunk)

    return h.hexdigest()


drive_to_repo = {
    "raw_dataset":
        (
            os.path.join(
                PROJECT_DIR,
                "dataset",
                "hf_bangla_smishing.csv"
            ),
            os.path.join(
                REPO_DIR,
                "data",
                "raw",
                "hf_bangla_smishing.csv"
            )
        ),

    "train_processed":
        (
            os.path.join(
                PROJECT_DIR,
                "dataset",
                "train_processed.csv"
            ),
            os.path.join(
                REPO_DIR,
                "data",
                "processed",
                "train_processed.csv"
            )
        ),

    "val_processed":
        (
            os.path.join(
                PROJECT_DIR,
                "dataset",
                "val_processed.csv"
            ),
            os.path.join(
                REPO_DIR,
                "data",
                "processed",
                "val_processed.csv"
            )
        ),

    "test_processed":
        (
            os.path.join(
                PROJECT_DIR,
                "dataset",
                "test_processed.csv"
            ),
            os.path.join(
                REPO_DIR,
                "data",
                "processed",
                "test_processed.csv"
            )
        ),

    "scaler":
        (
            os.path.join(
                PROJECT_DIR,
                "models",
                "structured_feature_scaler.pkl"
            ),
            os.path.join(
                REPO_DIR,
                "artifacts",
                "structured_feature_scaler.pkl"
            )
        ),

    "preprocessing_config":
        (
            os.path.join(
                PROJECT_DIR,
                "results",
                "preprocessing_config.json"
            ),
            os.path.join(
                REPO_DIR,
                "preprocessing",
                "preprocessing_config.json"
            )
        ),

    "class_weights":
        (
            os.path.join(
                PROJECT_DIR,
                "results",
                "class_weights.json"
            ),
            os.path.join(
                REPO_DIR,
                "preprocessing",
                "class_weights.json"
            )
        ),

    "checkpoint":
        (
            os.path.join(
                PROJECT_DIR,
                "results",
                "preprocessing_checkpoint.json"
            ),
            os.path.join(
                REPO_DIR,
                "preprocessing",
                "preprocessing_checkpoint.json"
            )
        )
}

print("=" * 70)
print("GOOGLE DRIVE vs LOCAL GITHUB COPY")
print("=" * 70)

for name, (drive_path, github_path) in drive_to_repo.items():

    if not os.path.exists(drive_path):
        print(f"⚠️ {name}: Drive file missing")
        continue

    if not os.path.exists(github_path):
        print(f"❌ {name}: GitHub copy missing")
        continue

    drive_hash = sha256_file(drive_path)
    github_hash = sha256_file(github_path)

    if drive_hash == github_hash:
        print(f"✅ {name}: IDENTICAL")
    else:
        print(f"❌ {name}: DIFFERENT")

======================================================================
GOOGLE DRIVE vs LOCAL GITHUB COPY
======================================================================
✅ raw_dataset: IDENTICAL
✅ train_processed: IDENTICAL
✅ val_processed: IDENTICAL
✅ test_processed: IDENTICAL
✅ scaler: IDENTICAL
✅ preprocessing_config: IDENTICAL
✅ class_weights: IDENTICAL
✅ checkpoint: IDENTICAL

In [ ]:
# ============================================================
# 10. FINAL GIT CHECK
# ============================================================

%cd /content/Multiclass-Bangla-Smishing-Detection

!git fetch origin main

print("=" * 70)
print("FINAL GIT STATUS")
print("=" * 70)

!git status

print("\nLatest local commit:")
!git log -1 --oneline

print("\nLatest GitHub commit:")
!git log -1 --oneline origin/main

/content/Multiclass-Bangla-Smishing-Detection
From https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection
 * branch            main       -> FETCH_HEAD
======================================================================
FINAL GIT STATUS
======================================================================
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Latest local commit:
8cecf3d (HEAD -> main, origin/main) Add completed preprocessing pipeline and project handoff

Latest GitHub commit:
8cecf3d (HEAD -> main, origin/main) Add completed preprocessing pipeline and project handoff

In [ ]:
!git fetch origin main
!git ls-tree -r --name-only origin/main

From https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection
 * branch            main       -> FETCH_HEAD
Bangla_Smishing_Project_Handoff_GitHub (1).md
Bangla_Smishing_Project_Handoff_GitHub.md
artifacts/structured_feature_scaler.pkl
data/processed/test_processed.csv
data/processed/train_processed.csv
data/processed/val_processed.csv
data/raw/hf_bangla_smishing.csv
preprocessing/class_weights.json
preprocessing/preprocessing_checkpoint.json
preprocessing/preprocessing_config.json

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [ ]:
# ============================================================
# FINAL PROJECT VERIFICATION
# Google Drive vs Local Repo vs Actual GitHub
# ============================================================

import os
import subprocess
import hashlib

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"
REPO_DIR = "/content/Multiclass-Bangla-Smishing-Detection"

# ------------------------------------------------------------
# 1. Make sure GitHub is up to date
# ------------------------------------------------------------

%cd "$REPO_DIR"

!git fetch origin main

# ------------------------------------------------------------
# 2. Get files from LOCAL repo
# ------------------------------------------------------------

local_files = []

for root, dirs, files in os.walk(REPO_DIR):
    dirs[:] = [d for d in dirs if d != ".git"]

    for file in files:
        full_path = os.path.join(root, file)

        relative = os.path.relpath(
            full_path,
            REPO_DIR
        ).replace("\\", "/")

        local_files.append(relative)

# ------------------------------------------------------------
# 3. Get files ACTUALLY on GitHub
# ------------------------------------------------------------

github_output = subprocess.check_output(
    [
        "git",
        "ls-tree",
        "-r",
        "--name-only",
        "origin/main"
    ],
    text=True
)

github_files = [
    x.strip()
    for x in github_output.splitlines()
    if x.strip()
]

local_set = set(local_files)
github_set = set(github_files)

# ------------------------------------------------------------
# 4. Print actual GitHub files
# ------------------------------------------------------------

print("=" * 70)
print("FILES ACTUALLY ON GITHUB")
print("=" * 70)

for f in sorted(github_files):
    print("✅", f)

# ------------------------------------------------------------
# 5. Files in local repo but NOT on GitHub
# ------------------------------------------------------------

only_local = sorted(
    local_set - github_set
)

print("\n" + "=" * 70)
print("LOCAL BUT NOT ON GITHUB")
print("=" * 70)

if only_local:
    for f in only_local:
        print("❌", f)
else:
    print("✅ None")

# ------------------------------------------------------------
# 6. Files on GitHub but NOT locally
# ------------------------------------------------------------

only_github = sorted(
    github_set - local_set
)

print("\n" + "=" * 70)
print("GITHUB BUT NOT LOCAL")
print("=" * 70)

if only_github:
    for f in only_github:
        print("⚠️", f)
else:
    print("✅ None")

# ------------------------------------------------------------
# 7. Important files check
# ------------------------------------------------------------

important_files = [
    "README.md",
    "requirements.txt",
    ".gitignore",

    "notebooks/Bangla_Smishing_Preprocessing.ipynb",

    "data/raw/hf_bangla_smishing.csv",

    "data/processed/train_processed.csv",
    "data/processed/val_processed.csv",
    "data/processed/test_processed.csv",

    "preprocessing/class_weights.json",
    "preprocessing/preprocessing_config.json",
    "preprocessing/preprocessing_checkpoint.json",

    "artifacts/structured_feature_scaler.pkl",

    "docs/Bangla_Smishing_Project_Handoff.md"
]

print("\n" + "=" * 70)
print("IMPORTANT FILES")
print("=" * 70)

all_important_ok = True

for f in important_files:

    exists_local = f in local_set
    exists_github = f in github_set

    if exists_local and exists_github:
        print("✅", f)

    elif exists_local:
        print("⚠️ LOCAL ONLY:", f)
        all_important_ok = False

    elif exists_github:
        print("⚠️ GITHUB ONLY:", f)
        all_important_ok = False

    else:
        print("❌ MISSING:", f)
        all_important_ok = False

# ------------------------------------------------------------
# 8. Commit synchronization
# ------------------------------------------------------------

local_commit = subprocess.check_output(
    ["git", "rev-parse", "HEAD"],
    text=True
).strip()

remote_commit = subprocess.check_output(
    ["git", "rev-parse", "origin/main"],
    text=True
).strip()

print("\n" + "=" * 70)
print("COMMIT SYNCHRONIZATION")
print("=" * 70)

print("Local commit :", local_commit)
print("GitHub commit:", remote_commit)

if local_commit == remote_commit:
    print("✅ Local repo and GitHub are synchronized.")
else:
    print("⚠️ Local repo and GitHub are NOT synchronized.")

# ------------------------------------------------------------
# 9. Git working tree
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("GIT STATUS")
print("=" * 70)

status = subprocess.run(
    ["git", "status", "--porcelain"],
    capture_output=True,
    text=True
)

if status.stdout.strip():
    print(status.stdout)
else:
    print("✅ Working tree clean.")

# ------------------------------------------------------------
# 10. FINAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RESULT")
print("=" * 70)

if (
    not only_local
    and
    all_important_ok
    and
    local_commit == remote_commit
    and
    not status.stdout.strip()
):
    print("🎉 EVERYTHING IS UPLOADED AND SYNCHRONIZED!")
else:
    print("⚠️ SOMETHING STILL NEEDS ATTENTION.")

/content/Multiclass-Bangla-Smishing-Detection
From https://github.com/Humaira201/Multiclass-Bangla-Smishing-Detection
 * branch            main       -> FETCH_HEAD
======================================================================
FILES ACTUALLY ON GITHUB
======================================================================
✅ Bangla_Smishing_Project_Handoff_GitHub (1).md
✅ Bangla_Smishing_Project_Handoff_GitHub.md
✅ artifacts/structured_feature_scaler.pkl
✅ data/processed/test_processed.csv
✅ data/processed/train_processed.csv
✅ data/processed/val_processed.csv
✅ data/raw/hf_bangla_smishing.csv
✅ preprocessing/class_weights.json
✅ preprocessing/preprocessing_checkpoint.json
✅ preprocessing/preprocessing_config.json

======================================================================
LOCAL BUT NOT ON GITHUB
======================================================================
✅ None

======================================================================
GITHUB BUT NOT LOCAL
======================================================================
✅ None

======================================================================
IMPORTANT FILES
======================================================================
❌ MISSING: README.md
❌ MISSING: requirements.txt
❌ MISSING: .gitignore
❌ MISSING: notebooks/Bangla_Smishing_Preprocessing.ipynb
✅ data/raw/hf_bangla_smishing.csv
✅ data/processed/train_processed.csv
✅ data/processed/val_processed.csv
✅ data/processed/test_processed.csv
✅ preprocessing/class_weights.json
✅ preprocessing/preprocessing_config.json
✅ preprocessing/preprocessing_checkpoint.json
✅ artifacts/structured_feature_scaler.pkl
❌ MISSING: docs/Bangla_Smishing_Project_Handoff.md

======================================================================
COMMIT SYNCHRONIZATION
======================================================================
Local commit : 8cecf3d7baee1f326dbbf4812a6a7f5fd5fb7f1b
GitHub commit: 8cecf3d7baee1f326dbbf4812a6a7f5fd5fb7f1b
✅ Local repo and GitHub are synchronized.

======================================================================
GIT STATUS
======================================================================
✅ Working tree clean.

======================================================================
FINAL RESULT
======================================================================
⚠️ SOMETHING STILL NEEDS ATTENTION.

In [ ]:
import os

PROJECT_DIR = "/content/drive/MyDrive/Bangla_Smishing_Project"

print("NOTEBOOKS FOUND:\n")

for root, dirs, files in os.walk(PROJECT_DIR):
    for file in files:
        if file.endswith(".ipynb"):
            print(os.path.join(root, file))

NOTEBOOKS FOUND:

/content/drive/MyDrive/Bangla_Smishing_Project/notebooks/Bangla Smishing Detection - Main.ipynb

In [ ]:
import os
import shutil
import glob

REPO_DIR = "/content/Multiclass-Bangla-Smishing-Detection"

notebooks = glob.glob(
    os.path.join(
        PROJECT_DIR,
        "**",
        "*.ipynb"
    ),
    recursive=True
)

print("Found notebooks:")
for notebook in notebooks:
    print(" -", notebook)

if not notebooks:
    raise FileNotFoundError(
        "No notebook found in Google Drive project folder."
    )

SOURCE_NOTEBOOK = notebooks[0]

DEST_NOTEBOOK = os.path.join(
    REPO_DIR,
    "notebooks",
    "Bangla_Smishing_Preprocessing.ipynb"
)

os.makedirs(
    os.path.dirname(DEST_NOTEBOOK),
    exist_ok=True
)

shutil.copy2(
    SOURCE_NOTEBOOK,
    DEST_NOTEBOOK
)

print("\n✅ Notebook copied!")
print("From:", SOURCE_NOTEBOOK)
print("To:", DEST_NOTEBOOK)